{
  "hash": "6d2bf7d36566173faf9bd748091d341c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 1: Geospatial Analytics for Social Good: Application of Spatial and Spatio-temporal Point Patterns Analysis to discover the geographical distribution of Armed Conflict in Myanmar\"\nauthor: \"Brian Lim\"\ndate: \"September 8, 2024\"\ndate-modified: \"last-modified\"\ncategories:\n  - Analysis\n  - R\n  - sf\n  - tidyverse\n  - sfdep\n  - readxl\nformat: html\neditor: visual\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n  cache.lazy: false\n---\n\n\n## 2.1 Exercise Overview\n\n## 2.2 Data Acquisition\n\n## 2.3 Getting Started\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, raster, spatstat, tmap, tidyverse, RColorBrewer, ggplot2, sfdep, spdep)\n```\n:::\n\n\n## 2.4 Importing Data into R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthai_drug_offenses <- read.csv(\"data/archive/thai_drug_offenses_2017_2022.csv\")%>% \n  select(-province_th)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(thai_drug_offenses)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  fiscal_year   types_of_drug_offenses    no_cases       province_en       \n Min.   :2017   Length:7392            Min.   :    0.0   Length:7392       \n 1st Qu.:2018   Class :character       1st Qu.:    1.0   Class :character  \n Median :2020   Mode  :character       Median :   70.0   Mode  :character  \n Mean   :2020                          Mean   :  535.3                     \n 3rd Qu.:2021                          3rd Qu.:  623.0                     \n Max.   :2022                          Max.   :17131.0                     \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_summary <- thai_drug_offenses %>%\n  group_by(fiscal_year, province_en, types_of_drug_offenses) %>%\n  summarize(no_cases = sum(no_cases, na.rm = TRUE), .groups = 'drop')\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nregions_sf <- st_read(dsn = \"data/tha_adm_rtsd_itos_20210121_shp\", \n                layer = \"tha_admbnda_adm1_rtsd_20220121\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `tha_admbnda_adm1_rtsd_20220121' from data source \n  `C:\\Users\\blzll\\OneDrive\\Desktop\\Y3S1\\IS415\\Quarto\\IS415\\Take-home_ex\\Take-home_ex02\\data\\tha_adm_rtsd_itos_20210121_shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 77 features and 16 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(regions_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"latitude\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"longitude\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nst_geometry_type(regions_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n [6] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[11] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[16] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[21] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[26] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[31] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[36] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[41] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[46] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[51] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[56] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[61] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[66] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[71] MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON MULTIPOLYGON\n[76] MULTIPOLYGON MULTIPOLYGON\n18 Levels: GEOMETRY POINT LINESTRING POLYGON MULTIPOINT ... TRIANGLE\n```\n\n\n:::\n:::\n\n\n## 2.5 Data Wrangling\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function to check province differences\nprov_diff <- function(thai_drug_offenses_provinces, regions_sf_provinces) {\n  # Create sets for efficient comparison\n  drug_set <- unique(thai_drug_offenses_provinces)\n  regions_set <- unique(regions_sf_provinces)\n  \n  # Check for mismatches\n  missing_in_regions <- setdiff(drug_set, regions_set)\n  missing_in_drug <- setdiff(regions_set, drug_set)\n  \n  if (length(missing_in_regions) == 0 && length(missing_in_drug) == 0) {\n    cat(\"All province names match.\\n\")\n  } else {\n    cat(\"There are mismatches in province names.\\n\")\n    if (length(missing_in_regions) > 0) {\n      cat(\"Missing in regions_sf:\", paste(missing_in_regions, collapse = \", \"), \"\\n\")\n    }\n    if (length(missing_in_drug) > 0) {\n      cat(\"Missing in drug_sf:\", paste(missing_in_drug, collapse = \", \"), \"\\n\")\n    }\n  }\n}\n\nprov_diff(unique(thai_drug_offenses$province_en), unique(regions_sf$ADM1_EN))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nThere are mismatches in province names.\nMissing in regions_sf: Loburi, buogkan \nMissing in drug_sf: Lop Buri, Bueng Kan \n```\n\n\n:::\n:::\n\n\nBased on the derived results, we would need to reassign the misaligned values such that they match exactly. In the code chunk below, we will perform the reassignment in the regions_sf\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthai_drug_offenses <- thai_drug_offenses %>%\n  mutate(province_en = case_when(\n    province_en == \"Loburi\" ~ \"Lop Buri\",\n    province_en == \"buogkan\" ~ \"Bueng Kan\",\n    TRUE ~ province_en\n  ))\n\nprov_diff(unique(thai_drug_offenses$province_en), unique(regions_sf$ADM1_EN))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAll province names match.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_region_1 <- left_join(thai_drug_offenses, regions_sf, by = c(\"province_en\" = \"ADM1_EN\")) %>%\n  select(1:6, \"date\", \"geometry\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check for null values in key columns\nna_count <- drug_region_1 %>%\n  summarise(na_geometry = sum(is.na(geometry)),\n            na_province = sum(is.na(province_en)),\n            na_drug_offense = sum(is.na(types_of_drug_offenses)),\n            na_cases = sum(is.na(no_cases)))\n\nprint(na_count)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  na_geometry na_province na_drug_offense na_cases\n1           0           0               0        0\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nduplicates <- drug_region_1 %>%\n  group_by(province_en, fiscal_year, types_of_drug_offenses) %>%\n  filter(n() > 1) %>%\n  ungroup()\n\nif (nrow(duplicates) > 0) {\n  cat(\"Duplicates found:\\n\")\n  print(duplicates)\n} else {\n  cat(\"No duplicates found.\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNo duplicates found.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# check if drug_region_1 is an sf object\nst_crs(drug_region_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System: NA\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert data frame to sf object and specify the CRS (EPSG:4326)\ndrug_region_thailand_sf <- st_as_sf(drug_region_1, crs = 4326)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(drug_region_thailand_sf, \"data/rds/drug_region_thailand_sf.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_region_thailand_sf <- read_rds(\"data/rds/drug_region_thailand_sf.rds\")\n```\n:::\n\n\n## 2.6 Global Measures of Spatial Autocorrelation\n\nGlobal measures of spatial autocorrelation, such as Moran’s I and Geary’s C, are critical in understanding the overall spatial structure of geographic data. They help detect patterns of clustering or dispersion by assessing whether similar values occur near each other across an entire study area. This insight is essential for identifying spatial dependencies and guiding decisions in fields like epidemiology, economics, and environmental science. By quantifying spatial relationships on a broad scale, global measures provide a foundational perspective for spatial analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnum_colors <- length(unique(regions_sf$ADM1_EN))\ncolors <- brewer.pal(n = num_colors, name = \"Set1\")\n\n# as there are 77 provinces in thailand\ntmap_options(max.categories = 77)\n\ntm_shape(regions_sf) +\n  tm_polygons(col = \"ADM1_EN\", palette = colors) +\n  tm_layout(main.title = \"Provinces in Thailand\",\n            main.title.position = \"center\",\n            main.title.size = 1.6,\n            legend.outside = TRUE) +\n  tm_legend(title = \"Provinces\")\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-15-1.png){width=1152}\n:::\n:::\n\n\n### 2.6.1 Defining Scope of Analysis\n\nTo ensure a data-driven analysis of drug-related offenses, we aim to focus exclusively on cases that have resulted in concrete legal outcomes, such as convictions or possession cases. Cases based solely on suspicion may not lead to prosecution or final legal action, potentially inflating the data without accurately reflecting the true extent of confirmed criminal activity. By narrowing our scope to finalized or substantiated cases, we intend to provide more reliable insights into the patterns of drug-related crime and its impact.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Group by types_of_drug_offenses and summarize by summing the no_cases\ntop_drug_offenses <- thai_drug_offenses %>%\n  filter(!grepl(\"suspect\", types_of_drug_offenses, ignore.case = TRUE)) %>%\n  group_by(types_of_drug_offenses) %>%\n  summarise(total_cases = sum(no_cases, na.rm = TRUE)) %>%\n  arrange(desc(total_cases))\n\n# View non-suspicion based types of drug offenses\ntop_drug_offenses\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 2\n  types_of_drug_offenses                     total_cases\n  <chr>                                            <int>\n1 drug_use_cases                                  915529\n2 possession_cases                                538893\n3 possession_with_intent_to_distribute_cases      341283\n4 trafficking_cases                                68379\n5 production_cases                                 56892\n6 conspiracy_cases                                   920\n7 import_cases                                       860\n8 export_cases                                        84\n```\n\n\n:::\n:::\n\n\nWe are further refining our analysis exclusively on **drug use cases**. This choice is driven by the nature of these offenses, which represent direct instances of illicit drug consumption and are critical to understanding the broader context of drug-related issues in Thailand. Unlike cases that involve suspicion or potential possession, drug use cases have clear legal implications and societal impacts, making them essential for our analysis. By focusing solely on these confirmed instances, we aim to provide accurate insights into the patterns of drug use and its repercussions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_region_thailand_sf <- drug_region_thailand_sf %>% filter(types_of_drug_offenses == \"drug_use_cases\")\n```\n:::\n\n\nFocusing exclusively on drug use cases allows us to concentrate our efforts on a significant area of concern, thereby providing clearer recommendations for law enforcement and policy development. This targeted approach ensures that our insights align with the most impactful drug-related offenses, facilitating more effective interventions and resource allocation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregion_2017_sf <- drug_region_thailand_sf %>% filter(fiscal_year == 2017)\nregion_2018_sf <- drug_region_thailand_sf %>% filter(fiscal_year == 2018)\nregion_2019_sf <- drug_region_thailand_sf %>% filter(fiscal_year == 2019)\nregion_2020_sf <- drug_region_thailand_sf %>% filter(fiscal_year == 2020)\nregion_2021_sf <- drug_region_thailand_sf %>% filter(fiscal_year == 2021)\nregion_2022_sf <- drug_region_thailand_sf %>% filter(fiscal_year == 2022)\n```\n:::\n\n\n### 2.6.2 Computing Contiguity Neighbours\n\n#### Year 2017\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthailand_nb_q <- st_contiguity(region_2017_sf, queen=TRUE)\nsummary(thailand_nb_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 77 \nNumber of nonzero links: 352 \nPercentage nonzero weights: 5.93692 \nAverage number of links: 4.571429 \n1 region with no links:\n68\n2 disjoint connected subgraphs\nLink number distribution:\n\n 0  1  2  3  4  5  6  7  8  9 \n 1  1  5 17 15 17 10  5  4  2 \n1 least connected region:\n14 with 1 link\n2 most connected regions:\n28 48 with 9 links\n```\n\n\n:::\n:::\n\n\n1 region with no links can be observed in the summary above. This is due to the **island province of Phuket** having no direct land neighbours, and being connected to **Phangnga province** via a bridge. As such, we can manually assign **Phuket** a neighbor, **Phangnga**, to help avoid issues in the spatial analysis, particularly with Moran's I, which requires each region to have at least one neighbor.\n\nThe following code chunk finds the index positions of the provinces \"Phuket\" and \"Phangnga\" within the `region_2017_sf` spatial data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphuket_index <- which(region_2017_sf$province_en == \"Phuket\")\nphangnga_index <- which(region_2017_sf$province_en == \"Phangnga\")\n```\n:::\n\n\nPurpose: This code modifies the neighborhood relationship between \"Phuket\" and \"Phangnga\" by manually assigning them as neighbors to each other within the `thailand_nb_q` object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthailand_nb_q[phuket_index][1] <- phangnga_index\nthailand_nb_q[phangnga_index][2] <- phuket_index\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(thailand_nb_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 77 \nNumber of nonzero links: 353 \nPercentage nonzero weights: 5.953786 \nAverage number of links: 4.584416 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 \n 2  5 17 15 17 10  5  4  2 \n2 least connected regions:\n14 68 with 1 link\n2 most connected regions:\n28 48 with 9 links\n```\n\n\n:::\n:::\n\n\nAs seen from the summary above all regions are linked and have at least 1 neighbour\n\n#### Computing Row-Standardised Weight Matrix\n\nNext, we need to assign spatial weights to each neighboring polygon.\n\n[`st_weights()`](https://rdrr.io/cran/sfdep/man/st_weights.html) function from `sfdep` packge can be used to supplement a neighbour list with spatial weights based on the chosen coding scheme. There are as least 5 different coding scheme styles supported by this function:\n\n-   `B` is the basic binary coding\n\n-   `W` is row standardised (sums over all links to n)\n\n-   `C` is globally standardised (sums over all links to n)\n\n-   `U` is equal to C divided by the number of neighbours (sums over all links to unity)\n\n-   `S` is the variance-stabilizing coding scheme proposed by Tiefelsdorf et al. (1999) (sums over all links to n).\n\nIn this study, we will use row-standardised weight matrix (style=`\"W\"`). Row standardisation of a matrix ensure that the sum of the values across each row add up to 1. This is accomplished by assigning the fraction 1/(# of neighbors) to each neighboring county then summing the weighted income values. Row standardisation ensures that all weights are between 0 and 1. This facilities the interpretation of operation with the weights matrix as an averaging of neighboring values, and allows for the spatial parameter used in our analyses to be comparable between models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthailand_wm_rs <- st_weights(thailand_nb_q, style = \"W\")\n```\n:::\n\n\nWe will mutate the newly created neighbour list object `thailand_nb_q` and weight matrix `thailand_wm_rs` into our existing `region_2017_sf`. The result will be a new object, which we will call `wm_q_<current-year>`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q_2017 <- region_2017_sf %>%\n  mutate(nb = thailand_nb_q,\n         wt = thailand_wm_rs,\n         .before = 1) \n```\n:::\n\n\n#### Global Moran's I\n\n::: panel-tabset\n## Global Moran's I\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoranI <- global_moran(wm_q_2017$no_cases,\n                        wm_q_2017$nb,\n                        wm_q_2017$wt)\nmoranI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$I\n[1] 0.08216344\n\n$K\n[1] 30.4821\n```\n\n\n:::\n:::\n\n\n## Global Moran's I test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_test_2017 <- global_moran_test(wm_q_2017$no_cases,\n                            wm_q_2017$nb,\n                            wm_q_2017$wt,\n                            alternative = \"greater\")\nglobal_moran_test_2017_statistics <- global_moran_test_2017$estimate[\"Moran I statistic\"]\nglobal_moran_test_2017_p_value <- global_moran_test_2017$p.value\nglobal_moran_test_2017\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw    \n\nMoran I statistic standard deviate = 1.5745, p-value = 0.05768\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.082163436      -0.013157895       0.003665038 \n```\n\n\n:::\n:::\n\n\nFor the year of **2017**, the Moran I statistic shows slight positive spatial autocorrelation, meaning there is some clustering of similar values of drug-related cases, but this clustering is weak and not statistically significant at the **5%** level (though close, with a p-value of **0.0577**). There is weak evidence suggesting that nearby provinces might have similar levels of drug-related cases, but the relationship is **not strong enough** to definitively **conclude spatial clustering**. As such, further investigation is needed to show stronger spatial autocorrelation.\n\n## Global Moran's I permutation test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(4242)\ngmoranMC_2017 <- global_moran_perm(wm_q_2017$no_cases,\n                  wm_q_2017$nb,\n                  wm_q_2017$wt,\n                  nsim = 999)\ngmoranMC_2017\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.082163, observed rank = 933, p-value = 0.134\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n:::\n\n##### Global Geary’s C\n\nIntroduced by Geary, Geary's C statistic studies the degree of intensity of a given feature in spatial objects described with the use of a weight matrix. Similarly to Moran's analysis, Geary's C can be used to quantify the extent of spatial autocorrelation in the data.\n\n::: panel-tabset\n## Global Geary's C test\n\nThe Global Geary's C test, which can be implemented using the `global_c_test()` function from the `sfdep` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_c_test_2017 <- global_c_test(wm_q_2017$no_cases,\n                                    wm_q_2017$nb,\n                                    wm_q_2017$wt,\n                                    alternative = \"greater\")\nglobal_c_test_2017_statistics <- global_c_test_2017$estimate [\"Geary C statistic\"]\nglobal_c_test_2017_p_value <- global_c_test_2017$p.value\nglobal_c_test_2017\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  x \nweights: listw   \n\nGeary C statistic standard deviate = -0.17983, p-value = 0.5714\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n       1.02584500        1.00000000        0.02065461 \n```\n\n\n:::\n:::\n\n\n## Global Geary's C Permutation Test\n\nSimilar to what we did in Moran's I test, we will use `global_c_perm()` function from **sfdep** package with `nsim = 999` which represent 1000 Monte Carlo simulations to be carried out.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(4242)\nbperm_2017 <- global_c_perm(wm_q_2017$no_cases,\n                  wm_q_2017$nb,\n                  wm_q_2017$wt,\n                  nsim = 999)\nbperm_2017\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 1.0258, observed rank = 565, p-value = 0.565\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n:::\n\n#### Year 2018\n\nSimilar that of 2017, we will compute a contiguity weight matrix for the study area, assigning spatial weights to each neighboring polygon, while also manually assigning \"Phuket\" and \"Phangnga\" as neighbours.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthailand_nb_q <- st_contiguity(region_2018_sf, queen=TRUE)\n```\n:::\n\n\nThe following code chunk finds the index positions of the provinces \"Phuket\" and \"Phangnga\" within the `region_2017_sf` spatial data frame, assigning them as neighbors to each other within the `thailand_nb_q` object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphuket_index <- which(region_2018_sf$province_en == \"Phuket\")\nphangnga_index <- which(region_2018_sf$province_en == \"Phangnga\")\n\nthailand_nb_q[phuket_index][1] <- phangnga_index\nthailand_nb_q[phangnga_index][2] <- phuket_index\n```\n:::\n\n\n#### Computing Row-Standardised Weight Matrix\n\nUsing the contiguity weight matrix, we will use row-standardised weight matrix (style = \"W\").\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthailand_wm_rs <- st_weights(thailand_nb_q, style = \"W\")\n```\n:::\n\n\nWe then mutate the newly created neighbour list object `thailand_nb_q` and weight matrix `thailand_wm_rs` into our existing `region_2018_sf`. The result will be a new object, which we will call `wm_q_<current-year>`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q_2018 <- region_2018_sf %>%\n  mutate(nb = thailand_nb_q,\n         wt = thailand_wm_rs,\n         .before = 1) \n```\n:::\n\n\n#### Global Moran's I\n\n::: panel-tabset\n## Global Moran's I\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoranI <- global_moran(wm_q_2018$no_cases,\n                        wm_q_2018$nb,\n                        wm_q_2018$wt)\nmoranI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$I\n[1] 0.09520252\n\n$K\n[1] 27.02001\n```\n\n\n:::\n:::\n\n\n## Global Moran's I test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_test_2018 <- global_moran_test(wm_q_2018$no_cases,\n                            wm_q_2018$nb,\n                            wm_q_2018$wt,\n                            alternative = \"greater\")\nglobal_moran_test_2018_statistics <- global_moran_test_2018$estimate[\"Moran I statistic\"]\nglobal_moran_test_2018_p_value <- global_moran_test_2018$p.value\nglobal_moran_test_2018\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw    \n\nMoran I statistic standard deviate = 1.7246, p-value = 0.0423\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.095202524      -0.013157895       0.003947668 \n```\n\n\n:::\n:::\n\n\nFor the year of **2017**, the Moran I statistic shows slight positive spatial autocorrelation, meaning there is some clustering of similar values of drug-related cases, but this clustering is weak and not statistically significant at the **5%** level (though close, with a p-value of **0.0577**). There is weak evidence suggesting that nearby provinces might have similar levels of drug-related cases, but the relationship is **not strong enough** to definitively **conclude spatial clustering**. As such, further investigation is needed to show stronger spatial autocorrelation.\n\n## Global Moran's I permutation test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(4242)\ngmoranMC_2018 <- global_moran_perm(wm_q_2018$no_cases,\n                  wm_q_2018$nb,\n                  wm_q_2018$wt,\n                  nsim = 999)\ngmoranMC_2018\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.095203, observed rank = 943, p-value = 0.114\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n:::\n\n### Global Geary’s C\n\nIntroduced by Geary, Geary's C statistic studies the degree of intensity of a given feature in spatial objects described with the use of a weight matrix. Similarly to Moran's analysis, Geary's C can be used to quantify the extent of spatial autocorrelation in the data.\n\n::: panel-tabset\n## Global Geary's C test\n\nThe Global Geary's C test, which can be implemented using the `global_c_test()` function from the `sfdep` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_c_test_2018 <- global_c_test(wm_q_2018$no_cases,\n                                    wm_q_2018$nb,\n                                    wm_q_2018$wt,\n                                    alternative = \"greater\")\nglobal_c_test_2018_statistics <- global_c_test_2018$estimate [\"Geary C statistic\"]\nglobal_c_test_2018_p_value <- global_c_test_2018$p.value\nglobal_c_test_2018\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  x \nweights: listw   \n\nGeary C statistic standard deviate = -0.026547, p-value = 0.5106\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n       1.00365196        1.00000000        0.01892375 \n```\n\n\n:::\n:::\n\n\n## Global Geary's C Permutation Test\n\nSimilar to what we did in Moran's I test, we will use `global_c_perm()` function from **sfdep** package with `nsim = 999` which represent 1000 Monte Carlo simulations to be carried out.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(4242)\nbperm_2018 <- global_c_perm(wm_q_2018$no_cases,\n                  wm_q_2018$nb,\n                  wm_q_2018$wt,\n                  nsim = 999)\nbperm_2018\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 1.0037, observed rank = 524, p-value = 0.524\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n:::\n\n### Year 2019\n\nSimilar that of 2017, we will compute a contiguity weight matrix for the study area, assigning spatial weights to each neighboring polygon, while also manually assigning \"Phuket\" and \"Phangnga\" as neighbours.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthailand_nb_q <- st_contiguity(region_2019_sf, queen=TRUE)\n```\n:::\n\n\nThe following code chunk finds the index positions of the provinces \"Phuket\" and \"Phangnga\" within the `region_2017_sf` spatial data frame, assigning them as neighbors to each other within the `thailand_nb_q` object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphuket_index <- which(region_2019_sf$province_en == \"Phuket\")\nphangnga_index <- which(region_2019_sf$province_en == \"Phangnga\")\n\nthailand_nb_q[phuket_index][1] <- phangnga_index\nthailand_nb_q[phangnga_index][2] <- phuket_index\n```\n:::\n\n\n#### Computing Row-Standardised Weight Matrix\n\nUsing the contiguity weight matrix, we will use row-standardised weight matrix (style = \"W\").\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthailand_wm_rs <- st_weights(thailand_nb_q, style = \"W\")\n```\n:::\n\n\nWe then mutate the newly created neighbour list object `thailand_nb_q` and weight matrix `thailand_wm_rs` into our existing `region_2018_sf`. The result will be a new object, which we will call `wm_q_<current-year>`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q_2019 <- region_2019_sf %>%\n  mutate(nb = thailand_nb_q,\n         wt = thailand_wm_rs,\n         .before = 1) \n```\n:::\n\n\n#### Global Moran's I\n\n::: panel-tabset\n## Global Moran's I\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoranI <- global_moran(wm_q_2019$no_cases,\n                        wm_q_2019$nb,\n                        wm_q_2019$wt)\nmoranI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$I\n[1] 0.1410203\n\n$K\n[1] 13.70039\n```\n\n\n:::\n:::\n\n\n## Global Moran's I test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_test_2019 <- global_moran_test(wm_q_2019$no_cases,\n                            wm_q_2019$nb,\n                            wm_q_2019$wt,\n                            alternative = \"greater\")\nglobal_moran_test_2019_statistics <- global_moran_test_2019$estimate[\"Moran I statistic\"]\nglobal_moran_test_2019_p_value <- global_moran_test_2019$p.value\nglobal_moran_test_2019\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw    \n\nMoran I statistic standard deviate = 2.1728, p-value = 0.0149\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.141020279      -0.013157895       0.005035023 \n```\n\n\n:::\n:::\n\n\nFor the year of **2017**, the Moran I statistic shows slight positive spatial autocorrelation, meaning there is some clustering of similar values of drug-related cases, but this clustering is weak and not statistically significant at the **5%** level (though close, with a p-value of **0.0577**). There is weak evidence suggesting that nearby provinces might have similar levels of drug-related cases, but the relationship is **not strong enough** to definitively **conclude spatial clustering**. As such, further investigation is needed to show stronger spatial autocorrelation.\n\n## Global Moran's I permutation test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(4242)\ngmoranMC_2019 <- global_moran_perm(wm_q_2019$no_cases,\n                  wm_q_2019$nb,\n                  wm_q_2019$wt,\n                  nsim = 999)\ngmoranMC_2019\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.14102, observed rank = 975, p-value = 0.05\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n:::\n\n### Global Geary’s C\n\nIntroduced by Geary, Geary's C statistic studies the degree of intensity of a given feature in spatial objects described with the use of a weight matrix. Similarly to Moran's analysis, Geary's C can be used to quantify the extent of spatial autocorrelation in the data.\n\n::: panel-tabset\n## Global Geary's C test\n\nThe Global Geary's C test, which can be implemented using the `global_c_test()` function from the `sfdep` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_c_test_2019 <- global_c_test(wm_q_2019$no_cases,\n                                    wm_q_2019$nb,\n                                    wm_q_2019$wt,\n                                    alternative = \"greater\")\nglobal_c_test_2019_statistics <- global_c_test_2019$estimate [\"Geary C statistic\"]\nglobal_c_test_2019_p_value <- global_c_test_2019$p.value\nglobal_c_test_2019\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  x \nweights: listw   \n\nGeary C statistic standard deviate = 0.7522, p-value = 0.226\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n       0.91669667        1.00000000        0.01226465 \n```\n\n\n:::\n:::\n\n\n## Global Geary's C Permutation Test\n\nSimilar to what we did in Moran's I test, we will use `global_c_perm()` function from **sfdep** package with `nsim = 999` which represent 1000 Monte Carlo simulations to be carried out.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(4242)\nbperm_2019 <- global_c_perm(wm_q_2019$no_cases,\n                  wm_q_2019$nb,\n                  wm_q_2019$wt,\n                  nsim = 999)\nbperm_2019\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.9167, observed rank = 204, p-value = 0.204\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n:::\n\n#### Year 2020\n\nSimilar that of 2017, we will compute a contiguity weight matrix for the study area, assigning spatial weights to each neighboring polygon, while also manually assigning \"Phuket\" and \"Phangnga\" as neighbours.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthailand_nb_q <- st_contiguity(region_2020_sf, queen=TRUE)\n```\n:::\n\n\nThe following code chunk finds the index positions of the provinces \"Phuket\" and \"Phangnga\" within the `region_2017_sf` spatial data frame, assigning them as neighbors to each other within the `thailand_nb_q` object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphuket_index <- which(region_2020_sf$province_en == \"Phuket\")\nphangnga_index <- which(region_2020_sf$province_en == \"Phangnga\")\n\nthailand_nb_q[phuket_index][1] <- phangnga_index\nthailand_nb_q[phangnga_index][2] <- phuket_index\n```\n:::\n\n\n#### Computing Row-Standardised Weight Matrix\n\nUsing the contiguity weight matrix, we will use row-standardised weight matrix (style = \"W\").\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthailand_wm_rs <- st_weights(thailand_nb_q, style = \"W\")\n```\n:::\n\n\nWe then mutate the newly created neighbour list object `thailand_nb_q` and weight matrix `thailand_wm_rs` into our existing `region_2018_sf`. The result will be a new object, which we will call `wm_q_<current-year>`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q_2020 <- region_2020_sf %>%\n  mutate(nb = thailand_nb_q,\n         wt = thailand_wm_rs,\n         .before = 1) \n```\n:::\n\n\n#### Global Moran's I\n\n::: panel-tabset\n## Global Moran's I\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoranI <- global_moran(wm_q_2020$no_cases,\n                        wm_q_2020$nb,\n                        wm_q_2020$wt)\nmoranI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$I\n[1] 0.0874654\n\n$K\n[1] 10.43646\n```\n\n\n:::\n:::\n\n\n## Global Moran's I test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_test_2020 <- global_moran_test(wm_q_2020$no_cases,\n                            wm_q_2020$nb,\n                            wm_q_2020$wt,\n                            alternative = \"greater\")\nglobal_moran_test_2020_statistics <- global_moran_test_2020$estimate[\"Moran I statistic\"]\nglobal_moran_test_2020_p_value <- global_moran_test_2020$p.value\nglobal_moran_test_2020\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw    \n\nMoran I statistic standard deviate = 1.382, p-value = 0.08349\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.087465400      -0.013157895       0.005301475 \n```\n\n\n:::\n:::\n\n\nFor the year of **2017**, the Moran I statistic shows slight positive spatial autocorrelation, meaning there is some clustering of similar values of drug-related cases, but this clustering is weak and not statistically significant at the **5%** level (though close, with a p-value of **0.0577**). There is weak evidence suggesting that nearby provinces might have similar levels of drug-related cases, but the relationship is **not strong enough** to definitively **conclude spatial clustering**. As such, further investigation is needed to show stronger spatial autocorrelation.\n\n## Global Moran's I permutation test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(4242)\ngmoranMC_2020 <- global_moran_perm(wm_q_2020$no_cases,\n                  wm_q_2020$nb,\n                  wm_q_2020$wt,\n                  nsim = 999)\ngmoranMC_2020\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.087465, observed rank = 903, p-value = 0.194\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n:::\n\n### Global Geary’s C\n\nIntroduced by Geary, Geary's C statistic studies the degree of intensity of a given feature in spatial objects described with the use of a weight matrix. Similarly to Moran's analysis, Geary's C can be used to quantify the extent of spatial autocorrelation in the data.\n\n::: panel-tabset\n## Global Geary's C test\n\nThe Global Geary's C test, which can be implemented using the `global_c_test()` function from the `sfdep` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_c_test_2020 <- global_c_test(wm_q_2020$no_cases,\n                                    wm_q_2020$nb,\n                                    wm_q_2020$wt,\n                                    alternative = \"greater\")\nglobal_c_test_2020_statistics <- global_c_test_2020$estimate [\"Geary C statistic\"]\nglobal_c_test_2020_p_value <- global_c_test_2020$p.value\nglobal_c_test_2020\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  x \nweights: listw   \n\nGeary C statistic standard deviate = 0.45817, p-value = 0.3234\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n       0.95275528        1.00000000        0.01063286 \n```\n\n\n:::\n:::\n\n\n## Global Geary's C Permutation Test\n\nSimilar to what we did in Moran's I test, we will use `global_c_perm()` function from **sfdep** package with `nsim = 999` which represent 1000 Monte Carlo simulations to be carried out.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(4242)\nbperm_2020 <- global_c_perm(wm_q_2020$no_cases,\n                  wm_q_2020$nb,\n                  wm_q_2020$wt,\n                  nsim = 999)\nbperm_2020\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.95276, observed rank = 308, p-value = 0.308\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n:::\n\n#### Year 2021\n\nSimilar that of 2017, we will compute a contiguity weight matrix for the study area, assigning spatial weights to each neighboring polygon, while also manually assigning \"Phuket\" and \"Phangnga\" as neighbours.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthailand_nb_q <- st_contiguity(region_2021_sf, queen=TRUE)\n```\n:::\n\n\nThe following code chunk finds the index positions of the provinces \"Phuket\" and \"Phangnga\" within the `region_2017_sf` spatial data frame, assigning them as neighbors to each other within the `thailand_nb_q` object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphuket_index <- which(region_2021_sf$province_en == \"Phuket\")\nphangnga_index <- which(region_2021_sf$province_en == \"Phangnga\")\n\nthailand_nb_q[phuket_index][1] <- phangnga_index\nthailand_nb_q[phangnga_index][2] <- phuket_index\n```\n:::\n\n\n#### Computing Row-Standardised Weight Matrix\n\nUsing the contiguity weight matrix, we will use row-standardised weight matrix (style = \"W\").\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthailand_wm_rs <- st_weights(thailand_nb_q, style = \"W\")\n```\n:::\n\n\nWe then mutate the newly created neighbour list object `thailand_nb_q` and weight matrix `thailand_wm_rs` into our existing `region_2018_sf`. The result will be a new object, which we will call `wm_q_<current-year>`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q_2021 <- region_2021_sf %>%\n  mutate(nb = thailand_nb_q,\n         wt = thailand_wm_rs,\n         .before = 1) \n```\n:::\n\n\n#### Global Moran's I\n\n::: panel-tabset\n## Global Moran's I\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoranI <- global_moran(wm_q_2021$no_cases,\n                        wm_q_2021$nb,\n                        wm_q_2021$wt)\nmoranI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$I\n[1] 0.2012584\n\n$K\n[1] 4.710498\n```\n\n\n:::\n:::\n\n\n## Global Moran's I test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_test_2021 <- global_moran_test(wm_q_2021$no_cases,\n                            wm_q_2021$nb,\n                            wm_q_2021$wt,\n                            alternative = \"greater\")\nglobal_moran_test_2021_statistics <- global_moran_test_2021$estimate[\"Moran I statistic\"]\nglobal_moran_test_2021_p_value <- global_moran_test_2021$p.value\nglobal_moran_test_2021\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw    \n\nMoran I statistic standard deviate = 2.823, p-value = 0.002379\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.201258399      -0.013157895       0.005768917 \n```\n\n\n:::\n:::\n\n\nFor the year of **2017**, the Moran I statistic shows slight positive spatial autocorrelation, meaning there is some clustering of similar values of drug-related cases, but this clustering is weak and not statistically significant at the **5%** level (though close, with a p-value of **0.0577**). There is weak evidence suggesting that nearby provinces might have similar levels of drug-related cases, but the relationship is **not strong enough** to definitively **conclude spatial clustering**. As such, further investigation is needed to show stronger spatial autocorrelation.\n\n## Global Moran's I permutation test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(4242)\ngmoranMC_2021 <- global_moran_perm(wm_q_2021$no_cases,\n                  wm_q_2021$nb,\n                  wm_q_2021$wt,\n                  nsim = 999)\ngmoranMC_2021\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.20126, observed rank = 993, p-value = 0.014\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n:::\n\n### Global Geary’s C\n\nIntroduced by Geary, Geary's C statistic studies the degree of intensity of a given feature in spatial objects described with the use of a weight matrix. Similarly to Moran's analysis, Geary's C can be used to quantify the extent of spatial autocorrelation in the data.\n\n::: panel-tabset\n## Global Geary's C test\n\nThe Global Geary's C test, which can be implemented using the `global_c_test()` function from the `sfdep` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_c_test_2021 <- global_c_test(wm_q_2021$no_cases,\n                                    wm_q_2021$nb,\n                                    wm_q_2021$wt,\n                                    alternative = \"greater\")\nglobal_c_test_2021_statistics <- global_c_test_2021$estimate [\"Geary C statistic\"]\nglobal_c_test_2021_p_value <- global_c_test_2021$p.value\nglobal_c_test_2021\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  x \nweights: listw   \n\nGeary C statistic standard deviate = 1.7139, p-value = 0.04328\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n       0.84892396        1.00000000        0.00777019 \n```\n\n\n:::\n:::\n\n\n## Global Geary's C Permutation Test\n\nSimilar to what we did in Moran's I test, we will use `global_c_perm()` function from **sfdep** package with `nsim = 999` which represent 1000 Monte Carlo simulations to be carried out.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(4242)\nbperm_2021 <- global_c_perm(wm_q_2021$no_cases,\n                  wm_q_2021$nb,\n                  wm_q_2021$wt,\n                  nsim = 999)\nbperm_2021\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.84892, observed rank = 35, p-value = 0.035\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n:::\n\n#### Year 2022\n\nSimilar that of 2017, we will compute a contiguity weight matrix for the study area, assigning spatial weights to each neighboring polygon, while also manually assigning \"Phuket\" and \"Phangnga\" as neighbours.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthailand_nb_q <- st_contiguity(region_2022_sf, queen=TRUE)\n```\n:::\n\n\nThe following code chunk finds the index positions of the provinces \"Phuket\" and \"Phangnga\" within the `region_2017_sf` spatial data frame, assigning them as neighbors to each other within the `thailand_nb_q` object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphuket_index <- which(region_2022_sf$province_en == \"Phuket\")\nphangnga_index <- which(region_2022_sf$province_en == \"Phangnga\")\n\nthailand_nb_q[phuket_index][1] <- phangnga_index\nthailand_nb_q[phangnga_index][2] <- phuket_index\n```\n:::\n\n\n#### Computing Row-Standardised Weight Matrix\n\nUsing the contiguity weight matrix, we will use row-standardised weight matrix (style = \"W\").\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthailand_wm_rs <- st_weights(thailand_nb_q, style = \"W\")\n```\n:::\n\n\nWe then mutate the newly created neighbour list object `thailand_nb_q` and weight matrix `thailand_wm_rs` into our existing `region_2018_sf`. The result will be a new object, which we will call `wm_q_<current-year>`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q_2022 <- region_2022_sf %>%\n  mutate(nb = thailand_nb_q,\n         wt = thailand_wm_rs,\n         .before = 1) \n```\n:::\n\n\n#### Global Moran's I\n\n::: panel-tabset\n## Global Moran's I\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoranI <- global_moran(wm_q_2022$no_cases,\n                        wm_q_2022$nb,\n                        wm_q_2022$wt)\nmoranI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$I\n[1] 0.2133052\n\n$K\n[1] 3.883933\n```\n\n\n:::\n:::\n\n\n## Global Moran's I test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_test_2022 <- global_moran_test(wm_q_2022$no_cases,\n                            wm_q_2022$nb,\n                            wm_q_2022$wt,\n                            alternative = \"greater\")\nglobal_moran_test_2022_statistics <- global_moran_test_2022$estimate[\"Moran I statistic\"]\nglobal_moran_test_2022_p_value <- global_moran_test_2022$p.value\nglobal_moran_test_2022\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw    \n\nMoran I statistic standard deviate = 2.9643, p-value = 0.001517\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.213305190      -0.013157895       0.005836395 \n```\n\n\n:::\n:::\n\n\nFor the year of **2017**, the Moran I statistic shows slight positive spatial autocorrelation, meaning there is some clustering of similar values of drug-related cases, but this clustering is weak and not statistically significant at the **5%** level (though close, with a p-value of **0.0577**). There is weak evidence suggesting that nearby provinces might have similar levels of drug-related cases, but the relationship is **not strong enough** to definitively **conclude spatial clustering**. As such, further investigation is needed to show stronger spatial autocorrelation.\n\n## Global Moran's I permutation test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(4242)\ngmoranMC_2022 <- global_moran_perm(wm_q_2022$no_cases,\n                  wm_q_2022$nb,\n                  wm_q_2022$wt,\n                  nsim = 999)\ngmoranMC_2022\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.21331, observed rank = 995, p-value = 0.01\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n:::\n\n### Global Geary’s C\n\nIntroduced by Geary, Geary's C statistic studies the degree of intensity of a given feature in spatial objects described with the use of a weight matrix. Similarly to Moran's analysis, Geary's C can be used to quantify the extent of spatial autocorrelation in the data.\n\n::: panel-tabset\n## Global Geary's C test\n\nThe Global Geary's C test, which can be implemented using the `global_c_test()` function from the `sfdep` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_c_test_2022 <- global_c_test(wm_q_2022$no_cases,\n                                    wm_q_2022$nb,\n                                    wm_q_2022$wt,\n                                    alternative = \"greater\")\nglobal_c_test_2022_statistics <- global_c_test_2022$estimate [\"Geary C statistic\"]\nglobal_c_test_2022_p_value <- global_c_test_2022$p.value\nglobal_c_test_2022\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  x \nweights: listw   \n\nGeary C statistic standard deviate = 1.8924, p-value = 0.02922\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n      0.837683654       1.000000000       0.007356952 \n```\n\n\n:::\n:::\n\n\n## Global Geary's C Permutation Test\n\nSimilar to what we did in Moran's I test, we will use `global_c_perm()` function from **sfdep** package with `nsim = 999` which represent 1000 Monte Carlo simulations to be carried out.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(4242)\nbperm_2022 <- global_c_perm(wm_q_2022$no_cases,\n                  wm_q_2022$nb,\n                  wm_q_2022$wt,\n                  nsim = 999)\nbperm_2022\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.83768, observed rank = 27, p-value = 0.027\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n:::\n\n### 2.6.3 Global Moran's I Permutation test\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# List of gmoranMC objects for each year\ngmoranMC_list <- list(gmoranMC_2017, gmoranMC_2018, gmoranMC_2019, \n                      gmoranMC_2020, gmoranMC_2021, gmoranMC_2022)\n\n# Corresponding year labels for the titles\nyear_labels <- c(\"2017\", \"2018\", \"2019\", \"2020\", \"2021\", \"2022\")\n\n# Set up the plotting area to have 3 rows and 2 columns for the six histograms\npar(mfrow = c(3, 2))\n\n# Loop through each year and plot the histogram\nfor (i in 1:length(gmoranMC_list)) {\n  gmoranMC <- gmoranMC_list[[i]]\n  year <- year_labels[i]\n  \n  # Plot the histogram for the current year\n  hist(gmoranMC$res, \n       main = paste(\"Global Moran's I MC Results\", year), \n       breaks = 20,\n       xlab = \"Monte-Carlo Results\", \n       ylab = \"Frequency\")\n  \n  # Add a vertical line for the observed Moran's I statistic\n  abline(v = gmoranMC$statistic, col = \"red\")\n}\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-75-1.png){width=1152}\n:::\n:::\n\n\n### 2.6.4 Global Geary's C Permutation test\n\n::: panel-tabset\n\n::: {.cell}\n\n```{.r .cell-code}\n# List of bperm objects for each year\ngmoranMC_list <- list(bperm_2017, bperm_2018, bperm_2019, \n                      bperm_2020, bperm_2021, bperm_2022)\n\n# Corresponding year labels for the titles\nyear_labels <- c(\"2017\", \"2018\", \"2019\", \"2020\", \"2021\", \"2022\")\n\n# Set up the plotting area to have 3 rows and 2 columns for the six histograms\npar(mfrow = c(3, 2))\n\n# Loop through each year and plot the histogram\nfor (i in 1:length(gmoranMC_list)) {\n  gmoranMC <- gmoranMC_list[[i]]\n  year <- year_labels[i]\n  \n  # Plot the histogram for the current year\n  hist(gmoranMC$res, \n       main = paste(\"Global Moran's I MC Results\", year),\n       breaks = 20,\n       xlab = \"Monte-Carlo Results\", \n       ylab = \"Frequency\")\n  \n  # Add a vertical line for the observed Moran's I statistic\n  abline(v = gmoranMC$statistic, col = \"red\")\n}\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-76-1.png){width=1152}\n:::\n:::\n\n:::\n\n### 2.6.5 Temporal Trends (2017-2022)\n\nWe can then analyze the spatial patterns of drug-related cases in Thailand over the period from 2017 to 2022 using Moran’s I and Geary’s C global spatial autocorrelation tests. The Moran’s I statistic identifies whether similar case values are clustered across regions, while Geary’s C focuses on local-level similarity, both crucial in understanding the distribution of drug-related offenses over time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a data frame to store Moran's I statistics and p-values\nmoran_i_results <- data.frame(\n  Year = c(2017, 2018, 2019, 2020, 2021, 2022),\n  Moran_I_Stat = c(global_moran_test_2017_statistics, global_moran_test_2018_statistics,\n                   global_moran_test_2019_statistics, global_moran_test_2020_statistics,\n                   global_moran_test_2021_statistics, global_moran_test_2022_statistics),\n  Moran_I_p_value = c(global_moran_test_2017_p_value, global_moran_test_2018_p_value,\n                      global_moran_test_2019_p_value, global_moran_test_2020_p_value,\n                      global_moran_test_2021_p_value, global_moran_test_2022_p_value)\n)\n\n# Consolidate the Geary C test data into a data frame\ngeary_c_results <- data.frame(\n  Year = c(2017, 2018, 2019, 2020, 2021, 2022),\n  Geary_C_Stat = c(global_c_test_2017_statistics, global_c_test_2018_statistics, \n                   global_c_test_2019_statistics, global_c_test_2020_statistics, \n                   global_c_test_2021_statistics, global_c_test_2022_statistics),\n  Geary_C_p_value = c(global_c_test_2017_p_value, global_c_test_2018_p_value, \n                      global_c_test_2019_p_value, global_c_test_2020_p_value, \n                      global_c_test_2021_p_value, global_c_test_2022_p_value)\n)\n```\n:::\n\n\n::: **Moran’s I (2017 - 2022)** 2017: Moran’s I = 0.0821, p-value = 0.0577 2018: Moran’s I = 0.0952, p-value = 0.0423 2019: Moran’s I = 0.1410, p-value = 0.0149 2020: Moran’s I = 0.0875, p-value = 0.0835 2021: Moran’s I = 0.2013, p-value = 0.0024 2022: Moran’s I = 0.2133, p-value = 0.0015\n\n**Geary’s C (2017 - 2022)** 2017: Geary’s C = 1.0258, p-value = 0.5714 2018: Geary’s C = 1.0037, p-value = 0.5106 2019: Geary’s C = 0.9167, p-value = 0.2260 2020: Geary’s C = 0.9528, p-value = 0.3234 2021: Geary’s C = 0.8489, p-value = 0.0433 2022: Geary’s C = 0.8377, p-value = 0.0292 :::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot Moran's I Statistic over the years\nggplot(moran_i_results, aes(x = Year, y = Moran_I_Stat)) +\n  geom_line() + \n  geom_point() +\n  labs(title = \"Moran's I Statistic Trend (2017-2022)\", \n       x = \"Year\", \n       y = \"Moran's I Statistic\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-78-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot p-values over the years\nggplot(moran_i_results, aes(x = Year, y = Moran_I_p_value)) +\n  geom_line() + \n  geom_point() +\n  geom_hline(yintercept = 0.05, linetype = \"dashed\", color = \"red\") +  # Significance threshold\n  labs(title = \"Moran's I Test p-values (2017-2022)\", \n       x = \"Year\", \n       y = \"p-value\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-79-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-tip title=\"Reflection\"}\n**Moran’s I (2017 - 2022)**\n\n**2017**: Moran’s I = 0.0821, p-value = 0.0577\n\n**2018**: Moran’s I = 0.0952, p-value = 0.0423\n\n**2019**: Moran’s I = 0.1410, p-value = 0.0149\n\n**2020**: Moran’s I = 0.0875, p-value = 0.0835\n\n**2021**: Moran’s I = 0.2013, p-value = 0.0024\n\n**2022**: Moran’s I = 0.2133, p-value = 0.0015\n\n**Key Insights**:\n\n-   **2017–2019**: There is a gradual increase in spatial autocorrelation, with clustering becoming statistically significant by **2018** and peaking in **2019**.\n\n-   **2020**: A slight drop in Moran’s I indicates weaker spatial clustering, and the p-value suggests the autocorrelation is no longer significant. This could indicate that drug-related cases became more dispersed or random in 2020.\n\n-   **2021–2022**: A sharp rise in Moran’s I shows that spatial clustering of drug-related cases became very strong in these years, and it is statistically significant with p-values well below 0.05. Drug-related cases are now highly concentrated in certain areas.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot Geary C Statistic over the years\nggplot(geary_c_results, aes(x = Year, y = Geary_C_Stat)) +\n  geom_line() + \n  geom_point() +\n  labs(title = \"Geary C Statistic Trend (2017-2022)\", \n       x = \"Year\", \n       y = \"Geary C Statistic\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-80-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot p-values over the years\nggplot(geary_c_results, aes(x = Year, y = Geary_C_p_value)) +\n  geom_line() + \n  geom_point() +\n  geom_hline(yintercept = 0.05, linetype = \"dashed\", color = \"red\") +  # Mark significance threshold\n  labs(title = \"Geary C Test p-values (2017-2022)\", \n       x = \"Year\", \n       y = \"p-value\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-81-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-tip title=\"Reflection\"}\n**Geary’s C (2017 - 2022)**\n\n**2017**: Geary’s C = 1.0258, p-value = 0.5714\n\n**2018**: Geary’s C = 1.0037, p-value = 0.5106\n\n**2019**: Geary’s C = 0.9167, p-value = 0.2260\n\n**2020**: Geary’s C = 0.9528, p-value = 0.3234\n\n**2021**: Geary’s C = 0.8489, p-value = 0.0433\n\n**2022**: Geary’s C = 0.8377, p-value = 0.0292\n\n**Key Insights**:\n\n-   **2017–2018**: Geary’s C values are very close to 1, indicating no significant spatial autocorrelation, meaning the distribution of drug-related cases was largely random.\n\n-   **2019**: The Geary’s C statistic starts to dip below 1, indicating emerging spatial autocorrelation, though it is not yet statistically significant.\n\n-   **2020**: Geary’s C rises slightly, indicating a slight weakening of spatial autocorrelation, but the cases are still mostly random with no significant clustering.\n\n-   **2021–2022**: A marked decrease in Geary’s C below 1, coupled with p-values dropping below 0.05, suggests significant clustering of similar values. This means that in the last two years, drug-related cases are no longer random and are now highly clustered.\n:::\n\n### 2.6.6 Conclusion\n\nFrom 2017 to 2022, both Moran’s I and Geary’s C statistics reveal an evolving spatial structure of drug-related cases. While earlier years exhibit weaker or random spatial patterns, by 2021 and 2022, significant clustering emerged, indicating an increase in spatial autocorrelation. This shift reflects that drug-related incidents are becoming more concentrated in specific areas, which could suggest targeted intervention zones for policy and law enforcement.\n\n## 2.7 Local Measures of Spatial Autocorrelation\n\nBuilding on the insights gained from global measures, local spatial autocorrelation focuses on identifying specific regions within the broader area that deviate from global trends. Techniques like Local Moran’s I allow for the detection of localized clusters and outliers, revealing spatial heterogeneity that might be masked by global statistics. This localized approach is crucial for pinpointing areas of high significance, enabling targeted interventions and more refined spatial decision-making.\n\n### 2.7.1 Local Moran's I\n\n::: panel-tabset\n## Year 2017\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(wm_q_2017)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 9 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 99.71972 ymin: 13.49339 xmax: 101.4044 ymax: 15.75613\nGeodetic CRS:  WGS 84\n                           nb\n1         3, 4, 7, 12, 57, 62\n2               9, 49, 55, 63\n3                 1, 4, 5, 57\n4          1, 3, 5, 8, 12, 15\n5      3, 4, 6, 8, 10, 57, 63\n6 5, 8, 9, 10, 19, 20, 49, 52\n                                                                           wt\n1            0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667\n2                                                      0.25, 0.25, 0.25, 0.25\n3                                                      0.25, 0.25, 0.25, 0.25\n4            0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667\n5 0.1428571, 0.1428571, 0.1428571, 0.1428571, 0.1428571, 0.1428571, 0.1428571\n6                      0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125\n  fiscal_year types_of_drug_offenses no_cases              province_en\n1        2017         drug_use_cases    11871                  Bangkok\n2        2017         drug_use_cases      200                 Chai Nat\n3        2017         drug_use_cases      553               Nonthaburi\n4        2017         drug_use_cases      450             Pathum Thani\n5        2017         drug_use_cases      378 Phra Nakhon Si Ayutthaya\n6        2017         drug_use_cases      727                 Lop Buri\n  Shape_Leng Shape_Area       date                       geometry\n1   2.417227 0.13133873 2019-02-18 MULTIPOLYGON (((100.6139 13...\n2   2.896316 0.20907828 2019-02-18 MULTIPOLYGON (((100.1199 15...\n3   1.251111 0.05323766 2019-02-18 MULTIPOLYGON (((100.3415 14...\n4   1.884945 0.12698345 2019-02-18 MULTIPOLYGON (((100.8916 14...\n5   3.041716 0.21393797 2019-02-18 MULTIPOLYGON (((100.5131 14...\n6   5.693342 0.54578838 2019-02-18 MULTIPOLYGON (((101.3453 15...\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa_2017 <- wm_q_2017 %>% \n  mutate(local_moran = local_moran(\n    no_cases, nb, wt, nsim = 99),\n         .before = 1) %>%\n  unnest(local_moran)\nlisa_2017\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 77 features and 21 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507\nGeodetic CRS:  WGS 84\n# A tibble: 77 × 22\n       ii      eii var_ii      z_ii       p_ii p_ii_sim p_folded_sim skewness\n    <dbl>    <dbl>  <dbl>     <dbl>      <dbl>    <dbl>        <dbl>    <dbl>\n 1 -0.556 -0.556   2.86   -0.000277 1.00           1            0.5     0.177\n 2  0.335  0.0252  0.0914  1.03     0.305          0.14         0.07   -2.31 \n 3 -0.652  0.00968 0.0460 -3.08     0.00204        0.08         0.04   -3.94 \n 4 -0.492 -0.0268  0.0433 -2.24     0.0253         0.14         0.07   -1.33 \n 5  0.171  0.00774 0.0434  0.783    0.434          0.38         0.19   -1.72 \n 6  0.122 -0.0118  0.0103  1.31     0.189          0.08         0.04   -1.32 \n 7 -0.929 -0.00761 0.0363 -4.83     0.00000134     0.04         0.02   -3.29 \n 8  0.142  0.0293  0.0635  0.447    0.655          0.78         0.39   -1.75 \n 9  0.329 -0.0562  0.118   1.12     0.261          0.06         0.03   -1.56 \n10  0.264  0.0409  0.0516  0.981    0.327          0.22         0.11   -1.70 \n# ℹ 67 more rows\n# ℹ 14 more variables: kurtosis <dbl>, mean <fct>, median <fct>, pysal <fct>,\n#   nb <nb>, wt <list>, fiscal_year <int>, types_of_drug_offenses <chr>,\n#   no_cases <int>, province_en <chr>, Shape_Leng <dbl>, Shape_Area <dbl>,\n#   date <date>, geometry <MULTIPOLYGON [°]>\n```\n\n\n:::\n:::\n\n\n### Visualising Local Moran’s I_i\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ntm_shape(lisa_2017)+\n  tm_fill(\"ii\", \n          palette = c(\"#b7dce9\",\"#e1ecbb\",\"#f5f3a6\",\n                      \"#f8d887\",\"#ec9a64\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA,\n          legend.hist = TRUE, \n          legend.is.portrait = TRUE,\n          legend.hist.z = 0.1) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Province-level Spatial Autocorrelation of drug use cases in Thailand\",\n            main.title.position = \"center\",\n            main.title.size = 1.7,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1.8,\n            legend.text.size = 1.3,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1.5, size = 3, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1.2) +\n  tm_grid(labels.size = 1,alpha =0.2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-84-1.png){width=1440}\n:::\n:::\n\n\n### Visualising Local Moran’s I_i p-value\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ntm_shape(lisa_2017)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#b7dce9\",\"#c9e3d2\",\"#f5f3a6\",\"#ec9a64\",\"#d21b1c\"),\n          title = \"p-value\",\n          midpoint = NA,\n          legend.hist = TRUE, \n          legend.is.portrait = TRUE,\n          legend.hist.z = 0.1) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation of drug use cases in Thailand\",\n            main.title.position = \"center\",\n            main.title.size = 1.7,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1.8,\n            legend.text.size = 1.3,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1.5, size = 3, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1.2) +\n  tm_grid(labels.size = 1,alpha =0.2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-85-1.png){width=1152}\n:::\n:::\n\n\n### Visualising Statistically Significant Local Spatial Autocorrelation Map\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nlisa_2017_sig <- lisa_2017  %>%\n  filter(p_ii_sim < 0.05) %>% mutate(label = province_en)\n\ntm_shape(lisa_2017)+\n  tm_polygons() +\n  tm_borders(col = \"black\", alpha = 0.6)+\ntm_shape(lisa_2017_sig)+\n  tm_fill(\"ii\", \n          palette = c(\"#b7dce9\",\"#e1ecbb\",\"#f5f3a6\",\n                      \"#f8d887\",\"#ec9a64\",\"#d21b1c\"),\n          title = \"Local Moran's I (p < 0.05)\",\n          midpoint = NA,\n          legend.hist = TRUE, \n          legend.is.portrait = TRUE,\n          legend.hist.z = 0.1) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistically Significant Village-Level Spatial Autocorrelation Map of drug use cases in Thailand\",\n            main.title.position = \"center\",\n            main.title.size = 1.7,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1.8,\n            legend.text.size = 1.3,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1.5, size = 3, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1.2) +\n  tm_grid(labels.size = 1,alpha =0.2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-86-1.png){width=1152}\n:::\n:::\n\n\n## Year 2018\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(wm_q_2018)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 9 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 99.71972 ymin: 13.49339 xmax: 101.4044 ymax: 15.75613\nGeodetic CRS:  WGS 84\n                           nb\n1         3, 4, 7, 12, 57, 62\n2               9, 49, 55, 63\n3                 1, 4, 5, 57\n4          1, 3, 5, 8, 12, 15\n5      3, 4, 6, 8, 10, 57, 63\n6 5, 8, 9, 10, 19, 20, 49, 52\n                                                                           wt\n1            0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667\n2                                                      0.25, 0.25, 0.25, 0.25\n3                                                      0.25, 0.25, 0.25, 0.25\n4            0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667\n5 0.1428571, 0.1428571, 0.1428571, 0.1428571, 0.1428571, 0.1428571, 0.1428571\n6                      0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125\n  fiscal_year types_of_drug_offenses no_cases              province_en\n1        2018         drug_use_cases    16480                  Bangkok\n2        2018         drug_use_cases      422                 Chai Nat\n3        2018         drug_use_cases     1661               Nonthaburi\n4        2018         drug_use_cases     1823             Pathum Thani\n5        2018         drug_use_cases     1123 Phra Nakhon Si Ayutthaya\n6        2018         drug_use_cases     1850                 Lop Buri\n  Shape_Leng Shape_Area       date                       geometry\n1   2.417227 0.13133873 2019-02-18 MULTIPOLYGON (((100.6139 13...\n2   2.896316 0.20907828 2019-02-18 MULTIPOLYGON (((100.1199 15...\n3   1.251111 0.05323766 2019-02-18 MULTIPOLYGON (((100.3415 14...\n4   1.884945 0.12698345 2019-02-18 MULTIPOLYGON (((100.8916 14...\n5   3.041716 0.21393797 2019-02-18 MULTIPOLYGON (((100.5131 14...\n6   5.693342 0.54578838 2019-02-18 MULTIPOLYGON (((101.3453 15...\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa_2018 <- wm_q_2018 %>% \n  mutate(local_moran = local_moran(\n    no_cases, nb, wt, nsim = 99),\n         .before = 1) %>%\n  unnest(local_moran)\nlisa_2018\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 77 features and 21 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507\nGeodetic CRS:  WGS 84\n# A tibble: 77 × 22\n         ii       eii    var_ii   z_ii       p_ii p_ii_sim p_folded_sim skewness\n      <dbl>     <dbl>     <dbl>  <dbl>      <dbl>    <dbl>        <dbl>    <dbl>\n 1  0.192   -0.698    2.57       0.555 0.579          0.56         0.28     1.06\n 2  0.358   -0.0462   0.150      1.04  0.298          0.1          0.05    -1.58\n 3 -0.188    0.00597  0.00219   -4.15  0.0000339      0.04         0.02    -1.71\n 4 -0.0355  -0.00166  0.000350  -1.81  0.0710         0.12         0.06    -1.86\n 5  0.0580  -0.000659 0.0251     0.370 0.711          0.72         0.36    -2.77\n 6  0.00332 -0.00104  0.0000892  0.462 0.644          0.76         0.38    -1.00\n 7  1.74     0.00455  0.133      4.76  0.00000194     0.02         0.01     2.64\n 8 -0.0724  -0.0133   0.0648    -0.232 0.816          0.62         0.31    -1.28\n 9  0.280   -0.0451   0.119      0.944 0.345          0.28         0.14    -1.31\n10  0.178   -0.00253  0.0853     0.617 0.537          0.56         0.28    -2.08\n# ℹ 67 more rows\n# ℹ 14 more variables: kurtosis <dbl>, mean <fct>, median <fct>, pysal <fct>,\n#   nb <nb>, wt <list>, fiscal_year <int>, types_of_drug_offenses <chr>,\n#   no_cases <int>, province_en <chr>, Shape_Leng <dbl>, Shape_Area <dbl>,\n#   date <date>, geometry <MULTIPOLYGON [°]>\n```\n\n\n:::\n:::\n\n\n### Visualising Local Moran’s I_i\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ntm_shape(lisa_2018)+\n  tm_fill(\"ii\", \n          palette = c(\"#b7dce9\",\"#e1ecbb\",\"#f5f3a6\",\n                      \"#f8d887\",\"#ec9a64\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA,\n          legend.hist = TRUE, \n          legend.is.portrait = TRUE,\n          legend.hist.z = 0.1) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Province-level Spatial Autocorrelation of drug use cases in Thailand\",\n            main.title.position = \"center\",\n            main.title.size = 1.7,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1.8,\n            legend.text.size = 1.3,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1.5, size = 3, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1.2) +\n  tm_grid(labels.size = 1,alpha =0.2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-89-1.png){width=1440}\n:::\n:::\n\n\n### Visualising Local Moran’s I_i p-value\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ntm_shape(lisa_2018)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#b7dce9\",\"#c9e3d2\",\"#f5f3a6\",\"#ec9a64\",\"#d21b1c\"),\n          title = \"p-value\",\n          midpoint = NA,\n          legend.hist = TRUE, \n          legend.is.portrait = TRUE,\n          legend.hist.z = 0.1) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation of drug use cases in Thailand\",\n            main.title.position = \"center\",\n            main.title.size = 1.7,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1.8,\n            legend.text.size = 1.3,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1.5, size = 3, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1.2) +\n  tm_grid(labels.size = 1,alpha =0.2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-90-1.png){width=1152}\n:::\n:::\n\n\n### Visualising Statistically Significant Local Spatial Autocorrelation Map\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nlisa_2018_sig <- lisa_2018  %>%\n  filter(p_ii_sim < 0.05) %>% mutate(label = province_en)\n\ntm_shape(lisa_2018)+\n  tm_polygons() +\n  tm_borders(col = \"black\", alpha = 0.6)+\ntm_shape(lisa_2018_sig)+\n  tm_fill(\"ii\", \n          palette = c(\"#b7dce9\",\"#e1ecbb\",\"#f5f3a6\",\n                      \"#f8d887\",\"#ec9a64\",\"#d21b1c\"),\n          title = \"Local Moran's I (p < 0.05)\",\n          midpoint = NA,\n          legend.hist = TRUE, \n          legend.is.portrait = TRUE,\n          legend.hist.z = 0.1) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistically Significant Village-Level Spatial Autocorrelation Map of drug use cases in Thailand\",\n            main.title.position = \"center\",\n            main.title.size = 1.7,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1.8,\n            legend.text.size = 1.3,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1.5, size = 3, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1.2) +\n  tm_grid(labels.size = 1,alpha =0.2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-91-1.png){width=1152}\n:::\n:::\n\n## Year 2019\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(wm_q_2019)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 9 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 99.71972 ymin: 13.49339 xmax: 101.4044 ymax: 15.75613\nGeodetic CRS:  WGS 84\n                           nb\n1         3, 4, 7, 12, 57, 62\n2               9, 49, 55, 63\n3                 1, 4, 5, 57\n4          1, 3, 5, 8, 12, 15\n5      3, 4, 6, 8, 10, 57, 63\n6 5, 8, 9, 10, 19, 20, 49, 52\n                                                                           wt\n1            0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667\n2                                                      0.25, 0.25, 0.25, 0.25\n3                                                      0.25, 0.25, 0.25, 0.25\n4            0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667\n5 0.1428571, 0.1428571, 0.1428571, 0.1428571, 0.1428571, 0.1428571, 0.1428571\n6                      0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125\n  fiscal_year types_of_drug_offenses no_cases              province_en\n1        2019         drug_use_cases    15067                  Bangkok\n2        2019         drug_use_cases      957                 Chai Nat\n3        2019         drug_use_cases     1719               Nonthaburi\n4        2019         drug_use_cases     2994             Pathum Thani\n5        2019         drug_use_cases     2470 Phra Nakhon Si Ayutthaya\n6        2019         drug_use_cases     2262                 Lop Buri\n  Shape_Leng Shape_Area       date                       geometry\n1   2.417227 0.13133873 2019-02-18 MULTIPOLYGON (((100.6139 13...\n2   2.896316 0.20907828 2019-02-18 MULTIPOLYGON (((100.1199 15...\n3   1.251111 0.05323766 2019-02-18 MULTIPOLYGON (((100.3415 14...\n4   1.884945 0.12698345 2019-02-18 MULTIPOLYGON (((100.8916 14...\n5   3.041716 0.21393797 2019-02-18 MULTIPOLYGON (((100.5131 14...\n6   5.693342 0.54578838 2019-02-18 MULTIPOLYGON (((101.3453 15...\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa_2019 <- wm_q_2019 %>% \n  mutate(local_moran = local_moran(\n    no_cases, nb, wt, nsim = 99),\n         .before = 1) %>%\n  unnest(local_moran)\nlisa_2019\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 77 features and 21 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507\nGeodetic CRS:  WGS 84\n# A tibble: 77 × 22\n          ii       eii    var_ii    z_ii     p_ii p_ii_sim p_folded_sim skewness\n       <dbl>     <dbl>     <dbl>   <dbl>    <dbl>    <dbl>        <dbl>    <dbl>\n 1  0.341    -0.120    3.26       0.256   7.98e-1     0.82         0.41    0.345\n 2  0.306     0.0205   0.0632     1.13    2.57e-1     0.16         0.08   -0.804\n 3 -0.371    -0.00563  0.0205    -2.55    1.07e-2     0.06         0.03   -1.18 \n 4  0.216     0.00406  0.0187     1.55    1.21e-1     0.16         0.08    1.34 \n 5 -0.0149    0.00113  0.00101   -0.505   6.13e-1     0.7          0.35    1.61 \n 6 -0.000229 -0.000410 0.0000393  0.0290  9.77e-1     0.92         0.46   -1.07 \n 7  2.73     -0.0672   0.331      4.85    1.21e-6     0.02         0.01    1.77 \n 8 -0.270    -0.0119   0.0493    -1.16    2.46e-1     0.2          0.1    -0.921\n 9  0.318    -0.0251   0.108      1.05    2.95e-1     0.28         0.14   -0.924\n10  0.166    -0.0593   0.149      0.583   5.60e-1     0.64         0.32   -0.978\n# ℹ 67 more rows\n# ℹ 14 more variables: kurtosis <dbl>, mean <fct>, median <fct>, pysal <fct>,\n#   nb <nb>, wt <list>, fiscal_year <int>, types_of_drug_offenses <chr>,\n#   no_cases <int>, province_en <chr>, Shape_Leng <dbl>, Shape_Area <dbl>,\n#   date <date>, geometry <MULTIPOLYGON [°]>\n```\n\n\n:::\n:::\n\n\n### Visualising Local Moran’s I_i\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ntm_shape(lisa_2019)+\n  tm_fill(\"ii\", \n          palette = c(\"#b7dce9\",\"#e1ecbb\",\"#f5f3a6\",\n                      \"#f8d887\",\"#ec9a64\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA,\n          legend.hist = TRUE, \n          legend.is.portrait = TRUE,\n          legend.hist.z = 0.1) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Province-level Spatial Autocorrelation \\nof Drug related offenses in Thailand\",\n            main.title.position = \"center\",\n            main.title.size = 1.7,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1.8,\n            legend.text.size = 1.3,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1.5, size = 3, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1.2) +\n  tm_grid(labels.size = 1,alpha =0.2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-94-1.png){width=1440}\n:::\n:::\n\n\n### Visualising Local Moran’s I_i p-value\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ntm_shape(lisa_2019)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#b7dce9\",\"#c9e3d2\",\"#f5f3a6\",\"#ec9a64\",\"#d21b1c\"),\n          title = \"p-value\",\n          midpoint = NA,\n          legend.hist = TRUE, \n          legend.is.portrait = TRUE,\n          legend.hist.z = 0.1) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation of drug use cases in Thailand\",\n            main.title.position = \"center\",\n            main.title.size = 1.7,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1.8,\n            legend.text.size = 1.3,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1.5, size = 3, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1.2) +\n  tm_grid(labels.size = 1,alpha =0.2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-95-1.png){width=1152}\n:::\n:::\n\n\n### Visualising Statistically Significant Local Spatial Autocorrelation Map\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nlisa_2019_sig <- lisa_2019  %>%\n  filter(p_ii_sim < 0.05) %>% mutate(label = province_en)\n\ntm_shape(lisa_2019)+\n  tm_polygons() +\n  tm_borders(col = \"black\", alpha = 0.6)+\ntm_shape(lisa_2019_sig)+\n  tm_fill(\"ii\", \n          palette = c(\"#b7dce9\",\"#e1ecbb\",\"#f5f3a6\",\n                      \"#f8d887\",\"#ec9a64\",\"#d21b1c\"),\n          title = \"Local Moran's I (p < 0.05)\",\n          midpoint = NA,\n          legend.hist = TRUE, \n          legend.is.portrait = TRUE,\n          legend.hist.z = 0.1) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistically Significant Village-Level Spatial Autocorrelation Map of drug use cases in Thailand\",\n            main.title.position = \"center\",\n            main.title.size = 1.7,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1.8,\n            legend.text.size = 1.3,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1.5, size = 3, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1.2) +\n  tm_grid(labels.size = 1,alpha =0.2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-96-1.png){width=1152}\n:::\n:::\n\n\n## Year 2020\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(wm_q_2020)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 9 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 100.8333 ymin: 15.40482 xmax: 104.9787 ymax: 18.30525\nGeodetic CRS:  WGS 84\n                    nb\n1    3, 68, 71, 74, 75\n2 3, 5, 69, 72, 74, 76\n3 1, 2, 69, 70, 71, 74\n4  6, 7, 8, 21, 22, 75\n5  2, 6, 8, 74, 76, 77\n6          4, 5, 8, 77\n                                                                wt fiscal_year\n1                                          0.2, 0.2, 0.2, 0.2, 0.2        2020\n2 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667        2020\n3 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667        2020\n4 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667        2020\n5 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667        2020\n6                                           0.25, 0.25, 0.25, 0.25        2020\n  types_of_drug_offenses no_cases   province_en Shape_Leng Shape_Area\n1         drug_use_cases      897 Maha Sarakham   5.208452  0.4734445\n2         drug_use_cases     2487      Mukdahan   3.869429  0.3480789\n3         drug_use_cases     2141        Roi Et   6.840452  0.6599047\n4         drug_use_cases      874          Loei   8.105761  0.8931913\n5         drug_use_cases      930  Sakon Nakhon   7.835410  0.8100902\n6         drug_use_cases     1762     Nong Khai   6.288769  0.2789794\n        date                       geometry\n1 2019-02-18 MULTIPOLYGON (((103.1562 16...\n2 2019-02-18 MULTIPOLYGON (((104.2527 16...\n3 2019-02-18 MULTIPOLYGON (((104.314 16....\n4 2019-02-18 MULTIPOLYGON (((102.095 18....\n5 2019-02-18 MULTIPOLYGON (((103.5404 18...\n6 2019-02-18 MULTIPOLYGON (((103.2985 18...\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa_2020 <- wm_q_2020 %>% \n  mutate(local_moran = local_moran(\n    no_cases, nb, wt, nsim = 99),\n         .before = 1) %>%\n  unnest(local_moran)\nlisa_2020\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 77 features and 21 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507\nGeodetic CRS:  WGS 84\n# A tibble: 77 × 22\n        ii      eii   var_ii   z_ii   p_ii p_ii_sim p_folded_sim skewness\n     <dbl>    <dbl>    <dbl>  <dbl>  <dbl>    <dbl>        <dbl>    <dbl>\n 1 -0.0216  0.00525 0.0699   -0.102 0.919      0.72         0.36   -1.58 \n 2 -0.0896  0.0268  0.0317   -0.654 0.513      0.62         0.31    0.921\n 3 -0.0366 -0.0116  0.00478  -0.361 0.718      0.92         0.46    1.55 \n 4  0.0565 -0.0174  0.0481    0.337 0.736      0.92         0.46   -0.766\n 5  0.0349 -0.0470  0.0524    0.357 0.721      0.86         0.43   -0.521\n 6  0.0160 -0.00398 0.000508  0.884 0.377      0.38         0.19   -0.783\n 7 -0.121   0.00244 0.344    -0.210 0.834      0.62         0.31   -1.13 \n 8  0.0184 -0.00620 0.00174   0.592 0.554      0.7          0.35   -0.968\n 9  1.52   -0.0240  0.764     1.76  0.0779     0.18         0.09    1.62 \n10  0.325  -0.208   0.788     0.600 0.549      0.58         0.29    0.975\n# ℹ 67 more rows\n# ℹ 14 more variables: kurtosis <dbl>, mean <fct>, median <fct>, pysal <fct>,\n#   nb <nb>, wt <list>, fiscal_year <int>, types_of_drug_offenses <chr>,\n#   no_cases <int>, province_en <chr>, Shape_Leng <dbl>, Shape_Area <dbl>,\n#   date <date>, geometry <MULTIPOLYGON [°]>\n```\n\n\n:::\n:::\n\n\n### Visualising Local Moran’s I_i\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ntm_shape(lisa_2020)+\n  tm_fill(\"ii\", \n          palette = c(\"#b7dce9\",\"#e1ecbb\",\"#f5f3a6\",\n                      \"#f8d887\",\"#ec9a64\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA,\n          legend.hist = TRUE, \n          legend.is.portrait = TRUE,\n          legend.hist.z = 0.1) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Province-level Spatial Autocorrelation of drug use cases in Thailand\",\n            main.title.position = \"center\",\n            main.title.size = 1.7,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1.8,\n            legend.text.size = 1.3,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1.5, size = 3, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1.2) +\n  tm_grid(labels.size = 1,alpha =0.2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-99-1.png){width=1440}\n:::\n:::\n\n\n### Visualising Local Moran’s I_i p-value\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ntm_shape(lisa_2020)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#b7dce9\",\"#c9e3d2\",\"#f5f3a6\",\"#ec9a64\",\"#d21b1c\"),\n          title = \"p-value\",\n          midpoint = NA,\n          legend.hist = TRUE, \n          legend.is.portrait = TRUE,\n          legend.hist.z = 0.1) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation of drug use cases in Thailand\",\n            main.title.position = \"center\",\n            main.title.size = 1.7,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1.8,\n            legend.text.size = 1.3,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1.5, size = 3, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1.2) +\n  tm_grid(labels.size = 1,alpha =0.2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-100-1.png){width=1152}\n:::\n:::\n\n\n### Visualising Statistically Significant Local Spatial Autocorrelation Map\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nlisa_2020_sig <- lisa_2020  %>%\n  filter(p_ii_sim < 0.05) %>% mutate(label = province_en)\n\ntm_shape(lisa_2020)+\n  tm_polygons() +\n  tm_borders(col = \"black\", alpha = 0.6)+\ntm_shape(lisa_2020_sig)+\n  tm_fill(\"ii\", \n          palette = c(\"#b7dce9\",\"#e1ecbb\",\"#f5f3a6\",\n                      \"#f8d887\",\"#ec9a64\",\"#d21b1c\"),\n          title = \"Local Moran's I (p < 0.05)\",\n          midpoint = NA,\n          legend.hist = TRUE, \n          legend.is.portrait = TRUE,\n          legend.hist.z = 0.1) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistically Significant Village-Level Spatial Autocorrelation Map of drug use cases in Thailand\",\n            main.title.position = \"center\",\n            main.title.size = 1.7,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1.8,\n            legend.text.size = 1.3,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1.5, size = 3, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1.2) +\n  tm_grid(labels.size = 1,alpha =0.2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-101-1.png){width=1152}\n:::\n:::\n\n\n## Year 2021\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(wm_q_2021)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 9 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 99.71972 ymin: 13.47842 xmax: 101.4044 ymax: 15.75613\nGeodetic CRS:  WGS 84\n                          nb\n1              8, 48, 54, 62\n2               3, 4, 56, 77\n3        2, 4, 7, 11, 14, 77\n4      2, 3, 5, 7, 9, 56, 62\n5 4, 7, 8, 9, 18, 19, 48, 51\n6                     11, 77\n                                                                           wt\n1                                                      0.25, 0.25, 0.25, 0.25\n2                                                      0.25, 0.25, 0.25, 0.25\n3            0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667\n4 0.1428571, 0.1428571, 0.1428571, 0.1428571, 0.1428571, 0.1428571, 0.1428571\n5                      0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125\n6                                                                    0.5, 0.5\n  fiscal_year types_of_drug_offenses no_cases              province_en\n1        2021         drug_use_cases      763                 Chai Nat\n2        2021         drug_use_cases     3202               Nonthaburi\n3        2021         drug_use_cases     1747             Pathum Thani\n4        2021         drug_use_cases     1766 Phra Nakhon Si Ayutthaya\n5        2021         drug_use_cases     1925                 Lop Buri\n6        2021         drug_use_cases     2515             Samut Prakan\n  Shape_Leng Shape_Area       date                       geometry\n1   2.896316 0.20907828 2019-02-18 MULTIPOLYGON (((100.1199 15...\n2   1.251111 0.05323766 2019-02-18 MULTIPOLYGON (((100.3415 14...\n3   1.884945 0.12698345 2019-02-18 MULTIPOLYGON (((100.8916 14...\n4   3.041716 0.21393797 2019-02-18 MULTIPOLYGON (((100.5131 14...\n5   5.693342 0.54578838 2019-02-18 MULTIPOLYGON (((101.3453 15...\n6   1.695100 0.07926199 2019-02-18 MULTIPOLYGON (((100.7306 13...\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa_2021 <- wm_q_2021 %>% \n  mutate(local_moran = local_moran(\n    no_cases, nb, wt, nsim = 99),\n         .before = 1) %>%\n  unnest(local_moran)\nlisa_2021\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 77 features and 21 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507\nGeodetic CRS:  WGS 84\n# A tibble: 77 × 22\n        ii       eii  var_ii   z_ii   p_ii p_ii_sim p_folded_sim skewness\n     <dbl>     <dbl>   <dbl>  <dbl>  <dbl>    <dbl>        <dbl>    <dbl>\n 1  0.792   0.00596  0.214    1.70  0.0898     0.02         0.01   -1.01 \n 2  0.0221  0.000703 0.00144  0.564 0.573      0.62         0.31    0.560\n 3 -0.150   0.0216   0.0439  -0.822 0.411      0.42         0.21   -0.796\n 4  0.294  -0.0170   0.0452   1.46  0.144      0.1          0.05   -0.686\n 5  0.118  -0.0366   0.0269   0.942 0.346      0.42         0.21   -0.130\n 6 -0.321   0.0141   0.0197  -2.39  0.0168     0.08         0.04   -1.23 \n 7  0.0681 -0.0447   0.118    0.329 0.742      0.88         0.44   -0.530\n 8  0.718   0.00896  0.180    1.67  0.0948     0.06         0.03   -0.514\n 9  0.635  -0.00294  0.182    1.50  0.134      0.1          0.05   -0.361\n10 -0.125  -0.0131   0.0191  -0.813 0.416      0.46         0.23   -0.428\n# ℹ 67 more rows\n# ℹ 14 more variables: kurtosis <dbl>, mean <fct>, median <fct>, pysal <fct>,\n#   nb <nb>, wt <list>, fiscal_year <int>, types_of_drug_offenses <chr>,\n#   no_cases <int>, province_en <chr>, Shape_Leng <dbl>, Shape_Area <dbl>,\n#   date <date>, geometry <MULTIPOLYGON [°]>\n```\n\n\n:::\n:::\n\n\n### Visualising Local Moran’s I_i\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ntm_shape(lisa_2021)+\n  tm_fill(\"ii\", \n          palette = c(\"#b7dce9\",\"#e1ecbb\",\"#f5f3a6\",\n                      \"#f8d887\",\"#ec9a64\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA,\n          legend.hist = TRUE, \n          legend.is.portrait = TRUE,\n          legend.hist.z = 0.1) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Province-level Spatial Autocorrelation of drug use cases in Thailand\",\n            main.title.position = \"center\",\n            main.title.size = 1.7,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1.8,\n            legend.text.size = 1.3,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1.5, size = 3, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1.2) +\n  tm_grid(labels.size = 1,alpha =0.2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-104-1.png){width=1440}\n:::\n:::\n\n\n### Visualising Local Moran’s I_i p-value\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ntm_shape(lisa_2021)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#b7dce9\",\"#c9e3d2\",\"#f5f3a6\",\"#ec9a64\",\"#d21b1c\"),\n          title = \"p-value\",\n          midpoint = NA,\n          legend.hist = TRUE, \n          legend.is.portrait = TRUE,\n          legend.hist.z = 0.1) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation of drug use cases in Thailand\",\n            main.title.position = \"center\",\n            main.title.size = 1.7,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1.8,\n            legend.text.size = 1.3,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1.5, size = 3, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1.2) +\n  tm_grid(labels.size = 1,alpha =0.2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-105-1.png){width=1152}\n:::\n:::\n\n\n### Visualising Statistically Significant Local Spatial Autocorrelation Map\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nlisa_2021_sig <- lisa_2021  %>%\n  filter(p_ii_sim < 0.05) %>% mutate(label = province_en)\n\ntm_shape(lisa_2021)+\n  tm_polygons() +\n  tm_borders(col = \"black\", alpha = 0.6)+\ntm_shape(lisa_2021_sig)+\n  tm_fill(\"ii\", \n          palette = c(\"#b7dce9\",\"#e1ecbb\",\"#f5f3a6\",\n                      \"#f8d887\",\"#ec9a64\",\"#d21b1c\"),\n          title = \"Local Moran's I (p < 0.05)\",\n          midpoint = NA,\n          legend.hist = TRUE, \n          legend.is.portrait = TRUE,\n          legend.hist.z = 0.1) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistically Significant Village-Level Spatial Autocorrelation Map of drug use cases in Thailand\",\n            main.title.position = \"center\",\n            main.title.size = 1.7,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1.8,\n            legend.text.size = 1.3,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1.5, size = 3, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1.2) +\n  tm_grid(labels.size = 1,alpha =0.2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-106-1.png){width=1152}\n:::\n:::\n\n\n## Year 2022\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(wm_q_2022)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 9 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 98.18107 ymin: 7.467277 xmax: 104.2406 ymax: 17.10196\nGeodetic CRS:  WGS 84\n                                 nb\n1                    15, 22, 35, 68\n2             8, 19, 24, 29, 60, 62\n3                17, 19, 51, 67, 76\n4             6, 43, 44, 48, 57, 74\n5                17, 23, 37, 38, 66\n6 4, 11, 21, 28, 40, 43, 55, 71, 74\n                                                                                                 wt\n1                                                                            0.25, 0.25, 0.25, 0.25\n2                                  0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667\n3                                                                           0.2, 0.2, 0.2, 0.2, 0.2\n4                                  0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667\n5                                                                           0.2, 0.2, 0.2, 0.2, 0.2\n6 0.1111111, 0.1111111, 0.1111111, 0.1111111, 0.1111111, 0.1111111, 0.1111111, 0.1111111, 0.1111111\n  fiscal_year types_of_drug_offenses no_cases    province_en Shape_Leng\n1        2022         drug_use_cases      168          Krabi   8.207968\n2        2022         drug_use_cases     2755        Bangkok   2.417227\n3        2022         drug_use_cases     1476   Kanchanaburi   8.231963\n4        2022         drug_use_cases     3753        Kalasin   6.054797\n5        2022         drug_use_cases      623 Kamphaeng Phet   5.190935\n6        2022         drug_use_cases     3968      Khon Kaen   8.994164\n  Shape_Area       date                       geometry\n1  0.4092860 2019-02-18 MULTIPOLYGON (((99.11329 7....\n2  0.1313387 2019-02-18 MULTIPOLYGON (((100.6139 13...\n3  1.6314864 2019-02-18 MULTIPOLYGON (((98.58631 15...\n4  0.5833781 2019-02-18 MULTIPOLYGON (((103.584 17....\n5  0.7237269 2019-02-18 MULTIPOLYGON (((99.48875 16...\n6  0.8978068 2019-02-18 MULTIPOLYGON (((102.7072 17...\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa_2022 <- wm_q_2022 %>% \n  mutate(local_moran = local_moran(\n    no_cases, nb, wt, nsim = 99),\n         .before = 1) %>%\n  unnest(local_moran)\nlisa_2022\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 77 features and 21 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507\nGeodetic CRS:  WGS 84\n# A tibble: 77 × 22\n         ii      eii  var_ii    z_ii    p_ii p_ii_sim p_folded_sim skewness\n      <dbl>    <dbl>   <dbl>   <dbl>   <dbl>    <dbl>        <dbl>    <dbl>\n 1 -0.495    0.0421  0.444   -0.807  0.420       0.4          0.2    -0.466\n 2 -0.285   -0.0768  0.127   -0.583  0.560       0.64         0.32    0.291\n 3  0.0512   0.00517 0.00431  0.701  0.483       0.5          0.25   -0.297\n 4  2.11    -0.0493  0.468    3.16   0.00158     0.02         0.01    0.262\n 5  0.860    0.0105  0.187    1.96   0.0495      0.02         0.01   -1.03 \n 6  1.43    -0.0449  0.429    2.25   0.0247      0.08         0.04    0.448\n 7 -0.00992 -0.0208  0.0293   0.0636 0.949       0.96         0.48   -0.323\n 8 -0.00621  0.00133 0.00221 -0.160  0.873       0.82         0.41   -0.212\n 9  0.0762  -0.0114  0.435    0.133  0.894       0.8          0.4     0.411\n10  0.672    0.0337  0.197    1.44   0.150       0.1          0.05   -0.578\n# ℹ 67 more rows\n# ℹ 14 more variables: kurtosis <dbl>, mean <fct>, median <fct>, pysal <fct>,\n#   nb <nb>, wt <list>, fiscal_year <int>, types_of_drug_offenses <chr>,\n#   no_cases <int>, province_en <chr>, Shape_Leng <dbl>, Shape_Area <dbl>,\n#   date <date>, geometry <MULTIPOLYGON [°]>\n```\n\n\n:::\n:::\n\n\n### Visualising Local Moran’s I_i\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ntm_shape(lisa_2022)+\n  tm_fill(\"ii\", \n          palette = c(\"#b7dce9\",\"#e1ecbb\",\"#f5f3a6\",\n                      \"#f8d887\",\"#ec9a64\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA,\n          legend.hist = TRUE, \n          legend.is.portrait = TRUE,\n          legend.hist.z = 0.1) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Province-level Spatial Autocorrelation of drug use cases in Thailand\",\n            main.title.position = \"center\",\n            main.title.size = 1.7,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1.8,\n            legend.text.size = 1.3,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1.5, size = 3, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1.2) +\n  tm_grid(labels.size = 1,alpha =0.2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-109-1.png){width=1440}\n:::\n:::\n\n\n### Visualising Local Moran’s I_i p-value\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ntm_shape(lisa_2022)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#b7dce9\",\"#c9e3d2\",\"#f5f3a6\",\"#ec9a64\",\"#d21b1c\"),\n          title = \"p-value\",\n          midpoint = NA,\n          legend.hist = TRUE, \n          legend.is.portrait = TRUE,\n          legend.hist.z = 0.1) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation of drug use cases in Thailand\",\n            main.title.position = \"center\",\n            main.title.size = 1.7,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1.8,\n            legend.text.size = 1.3,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1.5, size = 3, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1.2) +\n  tm_grid(labels.size = 1,alpha =0.2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-110-1.png){width=1152}\n:::\n:::\n\n\n### Visualising Statistically Significant Local Spatial Autocorrelation Map\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nlisa_2022_sig <- lisa_2022  %>%\n  filter(p_ii_sim < 0.05) %>% mutate(label = province_en)\n\ntm_shape(lisa_2022)+\n  tm_polygons() +\n  tm_borders(col = \"black\", alpha = 0.6)+\ntm_shape(lisa_2022_sig)+\n  tm_fill(\"ii\", \n          palette = c(\"#b7dce9\",\"#e1ecbb\",\"#f5f3a6\",\n                      \"#f8d887\",\"#ec9a64\",\"#d21b1c\"),\n          title = \"Local Moran's I (p < 0.05)\",\n          midpoint = NA,\n          legend.hist = TRUE, \n          legend.is.portrait = TRUE,\n          legend.hist.z = 0.1) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistically Significant Village-Level Spatial Autocorrelation Map of drug use cases in Thailand\",\n            main.title.position = \"center\",\n            main.title.size = 1.7,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1.8,\n            legend.text.size = 1.3,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1.5, size = 3, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1.2) +\n  tm_grid(labels.size = 1,alpha =0.2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-111-1.png){width=1152}\n:::\n:::\n\n\n::: \n\n### Statistically Significant Local Spatial Autocorrelation Map (2017 - 2022)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load grid package for overall title\nlibrary(grid)\n\n# List of data for each year\nlisa_data <- list(\n  \"2017\" = list(lisa = lisa_2017, sig = lisa_2017_sig),\n  \"2018\" = list(lisa = lisa_2018, sig = lisa_2018_sig),\n  \"2019\" = list(lisa = lisa_2019, sig = lisa_2019_sig),\n  \"2020\" = list(lisa = lisa_2020, sig = lisa_2020_sig),\n  \"2021\" = list(lisa = lisa_2021, sig = lisa_2021_sig),\n  \"2022\" = list(lisa = lisa_2022, sig = lisa_2022_sig)\n)\n\n# Initialize an empty list to store tmap objects\nmaps <- list()\n\n# Loop through each year's data and create a map\nfor (year in names(lisa_data)) {\n  map <- tm_shape(lisa_data[[year]]$lisa) +\n    tm_polygons(id = \"label\") +\n    tm_borders(col = \"black\", alpha = 0.6) +\n  tm_shape(lisa_data[[year]]$sig) +\n    tm_fill(\"ii\", \n            palette = c(\"#b7dce9\",\"#e1ecbb\",\"#f5f3a6\",\n                        \"#f8d887\",\"#ec9a64\",\"#d21b1c\"),\n            title = paste(\"Local Moran's I\", year, \"(p < 0.05)\"),\n            midpoint = NA,\n            id = \"label\") +\n    tm_borders(col = \"black\", alpha = 0.6) +\n    # Add title to individual plot\n    tm_layout(title = paste(\"Year\", year), title.position = c(\"center\", \"top\"))\n  \n  # Store the map in the list\n  maps[[year]] <- map\n}\n\n# Arrange the maps side by side\ntmap_arrange(\n  maps$`2017`, maps$`2018`, maps$`2019`,\n  maps$`2020`, maps$`2021`, maps$`2022`,\n  ncol = 3\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-112-1.png){width=1152}\n:::\n:::\n\n\n\n### 2.7.2 Visualising Statistically Significant Local Spatial Autocorrelation Map (Regions)\n\n#### 2.7.2.1 Regionalising the province of Thailand\n\nThailand is variably divided into different sets of regions, the most notable of which are the six-region grouping used in geographic studies, and the four-region grouping consistent with the Monthon administrative regional grouping system formerly used by the Ministry of Interior. These regions are the largest subdivisions of the country.\n\nIn contrast to the administrative divisions of the provinces of Thailand, the regions no longer have an administrative character, but are used for statistical or academic purposes.\n\nA six-region system is commonly used for geographical and scientific purposes. This system dates to 1935. It was formalised in 1977 by the National Geographical Committee, which was appointed by the National Research Council. It divides the country into the following regions:\n\n-   Northern Thailand\n-   Northeastern Thailand\n-   Western Thailand\n-   Central Thailand\n-   Eastern Thailand\n-   Southern Thailand\n\nThe four-region system, used in some administrative and statistical contexts, and also as a loose cultural grouping, includes the western and eastern regions within the central region, while grouping the provinces of Sukhothai, Phitsanulok, Phichit, Kamphaeng Phet, Phetchabun, Nakhon Sawan, and Uthai Thani in the northern region. This is also the regional system most commonly used on national television, when discussing regional events. It divides the country into the following regions:\n\n-   Northern Thailand\n-   Northeastern Thailand (Isan)\n-   Central Thailand\n-   Southern Thailand\n\nThe Thai Meteorological Department divides the country into six regions for meteorological purposes. It differs from the four-region system in that the east is regarded as a separate region, the south is divided into east and west coasts, and Nakhon Sawan and Uthai Thani are grouped in the central region.\n\n![](data/distribution.png)\n\nGiven the geographical scope of the study, we will adopt a six-region geographical distribution, focusing on the provincial level. This approach not only allows for a regionally nuanced analysis but also reduces the computational load within the R environment, making the analysis more efficient.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define provinces for each region\nnortheastern <- c(\"Amnat Charoen\", \"Bueng Kan\", \"Buri Ram\", \"Chaiyaphum\", \"Kalasin\", \n                  \"Khon Kaen\", \"Loei\", \"Maha Sarakham\", \"Mukdahan\", \"Nakhon Phanom\", \n                  \"Nakhon Ratchasima\", \"Nong Bua Lam Phu\", \"Nong Khai\", \"Roi Et\", \n                  \"Sakon Nakhon\", \"Si Sa Ket\", \"Surin\", \"Ubon Ratchathani\", \"Udon Thani\", \n                  \"Yasothon\")\n\nnorthern <- c(\"Chiang Mai\", \"Chiang Rai\", \"Lampang\", \"Lamphun\", \"Mae Hong Son\", \n              \"Nan\", \"Phayao\", \"Phrae\", \"Uttaradit\")\n\nwestern <- c(\"Tak\", \"Kanchanaburi\", \"Ratchaburi\", \"Phetchaburi\", \"Prachuap Khiri Khan\")\n\ncentral <- c(\"Kamphaeng Phet\", \"Phetchabun\", \"Phichit\", \"Phitsanulok\", \"Sukhothai\", \n             \"Nakhon Sawan\", \"Uthai Thani\", \"Ang Thong\", \"Bangkok\", \"Chai Nat\", \n             \"Lop Buri\", \"Nakhon Pathom\", \"Nonthaburi\", \"Pathum Thani\", \n             \"Phra Nakhon Si Ayutthaya\", \"Samut Prakan\", \"Samut Sakhon\", \n             \"Samut Songkhram\", \"Saraburi\", \"Sing Buri\", \"Suphan Buri\", \"Nakhon Nayok\")\n\neastern <- c(\"Chachoengsao\", \"Chanthaburi\", \"Chon Buri\", \"Prachin Buri\", \"Rayong\", \n             \"Sa Kaeo\", \"Trat\")\n\nsouthern <- c(\"Chumphon\", \"Nakhon Si Thammarat\", \"Narathiwat\", \"Pattani\", \n              \"Phatthalung\", \"Songkhla\", \"Surat Thani\", \"Yala\", \"Krabi\", \n              \"Phangnga\", \"Phuket\", \"Ranong\", \"Satun\", \"Trang\")\n```\n:::\n\n\n::: panel-tabset\n## Year 2017\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnortheastern_lisa_2017 <- lisa_2017 %>% filter(province_en %in% northeastern)\nnorthern_lisa_2017 <- lisa_2017 %>% filter(province_en %in% northern)\nwestern_lisa_2017 <- lisa_2017 %>% filter(province_en %in% western)\ncentral_lisa_2017 <- lisa_2017 %>% filter(province_en %in% central)\neastern_lisa_2017 <- lisa_2017 %>% filter(province_en %in% eastern)\nsouthern_lisa_2017 <- lisa_2017 %>% filter(province_en %in% southern)\n\nnortheastern_lisa_2017_sig <- lisa_2017_sig %>% filter(province_en %in% northeastern)\nnorthern_lisa_2017_sig <- lisa_2017_sig %>% filter(province_en %in% northern)\nwestern_lisa_2017_sig <- lisa_2017_sig %>% filter(province_en %in% western)\ncentral_lisa_2017_sig <- lisa_2017_sig %>% filter(province_en %in% central)\neastern_lisa_2017_sig <- lisa_2017_sig %>% filter(province_en %in% eastern)\nsouthern_lisa_2017_sig <- lisa_2017_sig %>% filter(province_en %in% southern)\n```\n:::\n\n\n### Northeastern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nnortheastern_local <- tm_shape(northeastern_lisa_2017)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nnortheastern_sig <- tm_shape(northeastern_lisa_2017)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(northeastern_local,northeastern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-115-1.png){width=1152}\n:::\n:::\n\n\n### Northern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nnorthern_local <- tm_shape(northern_lisa_2017)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nnorthern_sig <- tm_shape(northern_lisa_2017)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(northern_local,northern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-116-1.png){width=1152}\n:::\n:::\n\n\n### Western Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nwestern_local <- tm_shape(western_lisa_2017)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nwestern_sig <- tm_shape(western_lisa_2017)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(western_local,western_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-117-1.png){width=1152}\n:::\n:::\n\n\n### Central Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ncentral_local <- tm_shape(central_lisa_2017)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ncentral_sig <- tm_shape(central_lisa_2017)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(central_local,central_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-118-1.png){width=1152}\n:::\n:::\n\n\n### Eastern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\neastern_local <- tm_shape(eastern_lisa_2017)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\neastern_sig <- tm_shape(eastern_lisa_2017)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(eastern_local,eastern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-119-1.png){width=1152}\n:::\n:::\n\n\n### Southern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nsouthern_local <- tm_shape(southern_lisa_2017)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nsouthern_sig <- tm_shape(southern_lisa_2017)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(southern_local,southern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-120-1.png){width=1152}\n:::\n:::\n\n\n### Analysis & Discussion\n\nThe central district\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ntm_shape(central_lisa_2017)+\n  tm_polygons(id=\"label\") +\n  tm_borders(col = \"black\", alpha = 0.6)+\ntm_shape(central_lisa_2017_sig)+\n  tm_fill(\"ii\", \n          palette = c(\"#b7dce9\",\"#e1ecbb\"),\n          title = \"Local Moran's I (p < 0.05)\",\n          midpoint = NA,\n          id=\"label\")+\n  tm_borders(col = \"black\", alpha = 0.6)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-121-1.png){width=672}\n:::\n:::\n\n\n## Year 2018\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnortheastern_lisa_2018 <- lisa_2018 %>% filter(province_en %in% northeastern)\nnorthern_lisa_2018 <- lisa_2018 %>% filter(province_en %in% northern)\nwestern_lisa_2018 <- lisa_2018 %>% filter(province_en %in% western)\ncentral_lisa_2018 <- lisa_2018 %>% filter(province_en %in% central)\neastern_lisa_2018 <- lisa_2018 %>% filter(province_en %in% eastern)\nsouthern_lisa_2018 <- lisa_2018 %>% filter(province_en %in% southern)\n\nnortheastern_lisa_2018_sig <- lisa_2018_sig %>% filter(province_en %in% northeastern)\nnorthern_lisa_2018_sig <- lisa_2018_sig %>% filter(province_en %in% northern)\nwestern_lisa_2018_sig <- lisa_2018_sig %>% filter(province_en %in% western)\ncentral_lisa_2018_sig <- lisa_2018_sig %>% filter(province_en %in% central)\neastern_lisa_2018_sig <- lisa_2018_sig %>% filter(province_en %in% eastern)\nsouthern_lisa_2018_sig <- lisa_2018_sig %>% filter(province_en %in% southern)\n```\n:::\n\n\n### Northeastern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nnortheastern_local <- tm_shape(northeastern_lisa_2018)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nnortheastern_sig <- tm_shape(northeastern_lisa_2018)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(northeastern_local,northeastern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-123-1.png){width=1152}\n:::\n:::\n\n\n### Northern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nnorthern_local <- tm_shape(northern_lisa_2018)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nnorthern_sig <- tm_shape(northern_lisa_2018)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(northern_local,northern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-124-1.png){width=1152}\n:::\n:::\n\n\n### Western Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nwestern_local <- tm_shape(western_lisa_2018)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nwestern_sig <- tm_shape(western_lisa_2018)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(western_local,western_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-125-1.png){width=1152}\n:::\n:::\n\n\n### Central Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ncentral_local <- tm_shape(central_lisa_2018)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ncentral_sig <- tm_shape(central_lisa_2018)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(central_local,central_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-126-1.png){width=1152}\n:::\n:::\n\n\n### Eastern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\neastern_local <- tm_shape(eastern_lisa_2018)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\neastern_sig <- tm_shape(eastern_lisa_2018)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(eastern_local,eastern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-127-1.png){width=1152}\n:::\n:::\n\n\n### Southern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nsouthern_local <- tm_shape(southern_lisa_2018)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nsouthern_sig <- tm_shape(southern_lisa_2018)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(southern_local,southern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-128-1.png){width=1152}\n:::\n:::\n\n\n### Analysis & Discussion\n\nThe central district\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ntm_shape(central_lisa_2018)+\n  tm_polygons(id=\"label\") +\n  tm_borders(col = \"black\", alpha = 0.6)+\ntm_shape(central_lisa_2018_sig)+\n  tm_fill(\"ii\", \n          palette = c(\"#b7dce9\",\"#e1ecbb\"),\n          title = \"Local Moran's I (p < 0.05)\",\n          midpoint = NA,\n          id=\"label\")+\n  tm_borders(col = \"black\", alpha = 0.6)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-129-1.png){width=672}\n:::\n:::\n\n\n## Year 2019\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnortheastern_lisa_2019 <- lisa_2019 %>% filter(province_en %in% northeastern)\nnorthern_lisa_2019 <- lisa_2019 %>% filter(province_en %in% northern)\nwestern_lisa_2019 <- lisa_2019 %>% filter(province_en %in% western)\ncentral_lisa_2019 <- lisa_2019 %>% filter(province_en %in% central)\neastern_lisa_2019 <- lisa_2019 %>% filter(province_en %in% eastern)\nsouthern_lisa_2019 <- lisa_2019 %>% filter(province_en %in% southern)\n\nnortheastern_lisa_2019_sig <- lisa_2019_sig %>% filter(province_en %in% northeastern)\nnorthern_lisa_2019_sig <- lisa_2019_sig %>% filter(province_en %in% northern)\nwestern_lisa_2019_sig <- lisa_2019_sig %>% filter(province_en %in% western)\ncentral_lisa_2019_sig <- lisa_2019_sig %>% filter(province_en %in% central)\neastern_lisa_2019_sig <- lisa_2019_sig %>% filter(province_en %in% eastern)\nsouthern_lisa_2019_sig <- lisa_2019_sig %>% filter(province_en %in% southern)\n```\n:::\n\n\n### Northeastern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nnortheastern_local <- tm_shape(northeastern_lisa_2019)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nnortheastern_sig <- tm_shape(northeastern_lisa_2019)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(northeastern_local,northeastern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-131-1.png){width=1152}\n:::\n:::\n\n\n### Northern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nnorthern_local <- tm_shape(northern_lisa_2019)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nnorthern_sig <- tm_shape(northern_lisa_2019)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(northern_local,northern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-132-1.png){width=1152}\n:::\n:::\n\n\n### Western Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nwestern_local <- tm_shape(western_lisa_2019)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nwestern_sig <- tm_shape(western_lisa_2019)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(western_local,western_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-133-1.png){width=1152}\n:::\n:::\n\n\n### Central Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ncentral_local <- tm_shape(central_lisa_2019)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ncentral_sig <- tm_shape(central_lisa_2019)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(central_local,central_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-134-1.png){width=1152}\n:::\n:::\n\n\n### Eastern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\neastern_local <- tm_shape(eastern_lisa_2019)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\neastern_sig <- tm_shape(eastern_lisa_2019)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(eastern_local,eastern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-135-1.png){width=1152}\n:::\n:::\n\n\n### Southern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nsouthern_local <- tm_shape(southern_lisa_2019)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nsouthern_sig <- tm_shape(southern_lisa_2019)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(southern_local,southern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-136-1.png){width=1152}\n:::\n:::\n\n\n### Analysis & Discussion\n\nThe central district\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ntm_shape(central_lisa_2019)+\n  tm_polygons(id=\"label\") +\n  tm_borders(col = \"black\", alpha = 0.6)+\ntm_shape(central_lisa_2019_sig)+\n  tm_fill(\"ii\", \n          palette = c(\"#b7dce9\",\"#e1ecbb\"),\n          title = \"Local Moran's I (p < 0.05)\",\n          midpoint = NA,\n          id=\"label\")+\n  tm_borders(col = \"black\", alpha = 0.6)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-137-1.png){width=672}\n:::\n:::\n\n\n## Year 2020\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnortheastern_lisa_2020 <- lisa_2020 %>% filter(province_en %in% northeastern)\nnorthern_lisa_2020 <- lisa_2020 %>% filter(province_en %in% northern)\nwestern_lisa_2020 <- lisa_2020 %>% filter(province_en %in% western)\ncentral_lisa_2020 <- lisa_2020 %>% filter(province_en %in% central)\neastern_lisa_2020 <- lisa_2020 %>% filter(province_en %in% eastern)\nsouthern_lisa_2020 <- lisa_2020 %>% filter(province_en %in% southern)\n\nnortheastern_lisa_2020_sig <- lisa_2020_sig %>% filter(province_en %in% northeastern)\nnorthern_lisa_2020_sig <- lisa_2020_sig %>% filter(province_en %in% northern)\nwestern_lisa_2020_sig <- lisa_2020_sig %>% filter(province_en %in% western)\ncentral_lisa_2020_sig <- lisa_2020_sig %>% filter(province_en %in% central)\neastern_lisa_2020_sig <- lisa_2020_sig %>% filter(province_en %in% eastern)\nsouthern_lisa_2020_sig <- lisa_2020_sig %>% filter(province_en %in% southern)\n```\n:::\n\n\n### Northeastern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nnortheastern_local <- tm_shape(northeastern_lisa_2020)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nnortheastern_sig <- tm_shape(northeastern_lisa_2020)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(northeastern_local,northeastern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-139-1.png){width=1152}\n:::\n:::\n\n\n### Northern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nnorthern_local <- tm_shape(northern_lisa_2020)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nnorthern_sig <- tm_shape(northern_lisa_2020)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(northern_local,northern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-140-1.png){width=1152}\n:::\n:::\n\n\n### Western Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nwestern_local <- tm_shape(western_lisa_2020)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nwestern_sig <- tm_shape(western_lisa_2020)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(western_local,western_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-141-1.png){width=1152}\n:::\n:::\n\n\n### Central Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ncentral_local <- tm_shape(central_lisa_2020)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ncentral_sig <- tm_shape(central_lisa_2020)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(central_local,central_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-142-1.png){width=1152}\n:::\n:::\n\n\n### Eastern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\neastern_local <- tm_shape(eastern_lisa_2020)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\neastern_sig <- tm_shape(eastern_lisa_2020)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(eastern_local,eastern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-143-1.png){width=1152}\n:::\n:::\n\n\n### Southern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nsouthern_local <- tm_shape(southern_lisa_2020)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nsouthern_sig <- tm_shape(southern_lisa_2020)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(southern_local,southern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-144-1.png){width=1152}\n:::\n:::\n\n\n### Analysis & Discussion\n\nThe central district\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ntm_shape(central_lisa_2020)+\n  tm_polygons(id=\"label\") +\n  tm_borders(col = \"black\", alpha = 0.6)+\ntm_shape(central_lisa_2020_sig)+\n  tm_fill(\"ii\", \n          palette = c(\"#b7dce9\",\"#e1ecbb\"),\n          title = \"Local Moran's I (p < 0.05)\",\n          midpoint = NA,\n          id=\"label\")+\n  tm_borders(col = \"black\", alpha = 0.6)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-145-1.png){width=672}\n:::\n:::\n\n\n## Year 2021\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnortheastern_lisa_2021 <- lisa_2021 %>% filter(province_en %in% northeastern)\nnorthern_lisa_2021 <- lisa_2021 %>% filter(province_en %in% northern)\nwestern_lisa_2021 <- lisa_2021 %>% filter(province_en %in% western)\ncentral_lisa_2021 <- lisa_2021 %>% filter(province_en %in% central)\neastern_lisa_2021 <- lisa_2021 %>% filter(province_en %in% eastern)\nsouthern_lisa_2021 <- lisa_2021 %>% filter(province_en %in% southern)\n\nnortheastern_lisa_2021_sig <- lisa_2021_sig %>% filter(province_en %in% northeastern)\nnorthern_lisa_2021_sig <- lisa_2021_sig %>% filter(province_en %in% northern)\nwestern_lisa_2021_sig <- lisa_2021_sig %>% filter(province_en %in% western)\ncentral_lisa_2021_sig <- lisa_2021_sig %>% filter(province_en %in% central)\neastern_lisa_2021_sig <- lisa_2021_sig %>% filter(province_en %in% eastern)\nsouthern_lisa_2021_sig <- lisa_2021_sig %>% filter(province_en %in% southern)\n```\n:::\n\n\n### Northeastern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nnortheastern_local <- tm_shape(northeastern_lisa_2021)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nnortheastern_sig <- tm_shape(northeastern_lisa_2021)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(northeastern_local,northeastern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-147-1.png){width=1152}\n:::\n:::\n\n\n### Northern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nnorthern_local <- tm_shape(northern_lisa_2021)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nnorthern_sig <- tm_shape(northern_lisa_2021)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(northern_local,northern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-148-1.png){width=1152}\n:::\n:::\n\n\n### Western Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nwestern_local <- tm_shape(western_lisa_2021)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nwestern_sig <- tm_shape(western_lisa_2021)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(western_local,western_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-149-1.png){width=1152}\n:::\n:::\n\n\n### Central Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ncentral_local <- tm_shape(central_lisa_2021)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ncentral_sig <- tm_shape(central_lisa_2021)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(central_local,central_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-150-1.png){width=1152}\n:::\n:::\n\n\n### Eastern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\neastern_local <- tm_shape(eastern_lisa_2021)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\neastern_sig <- tm_shape(eastern_lisa_2021)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(eastern_local,eastern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-151-1.png){width=1152}\n:::\n:::\n\n\n### Southern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nsouthern_local <- tm_shape(southern_lisa_2021)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nsouthern_sig <- tm_shape(southern_lisa_2021)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(southern_local,southern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-152-1.png){width=1152}\n:::\n:::\n\n\n### Analysis & Discussion\n\nThe central district\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ntm_shape(central_lisa_2021)+\n  tm_polygons(id=\"label\") +\n  tm_borders(col = \"black\", alpha = 0.6)+\ntm_shape(central_lisa_2021_sig)+\n  tm_fill(\"ii\", \n          palette = c(\"#b7dce9\",\"#e1ecbb\"),\n          title = \"Local Moran's I (p < 0.05)\",\n          midpoint = NA,\n          id=\"label\")+\n  tm_borders(col = \"black\", alpha = 0.6)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-153-1.png){width=672}\n:::\n:::\n\n\n## Year 2022\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnortheastern_lisa_2022 <- lisa_2022 %>% filter(province_en %in% northeastern)\nnorthern_lisa_2022 <- lisa_2022 %>% filter(province_en %in% northern)\nwestern_lisa_2022 <- lisa_2022 %>% filter(province_en %in% western)\ncentral_lisa_2022 <- lisa_2022 %>% filter(province_en %in% central)\neastern_lisa_2022 <- lisa_2022 %>% filter(province_en %in% eastern)\nsouthern_lisa_2022 <- lisa_2022 %>% filter(province_en %in% southern)\n\nnortheastern_lisa_2022_sig <- lisa_2022_sig %>% filter(province_en %in% northeastern)\nnorthern_lisa_2022_sig <- lisa_2022_sig %>% filter(province_en %in% northern)\nwestern_lisa_2022_sig <- lisa_2022_sig %>% filter(province_en %in% western)\ncentral_lisa_2022_sig <- lisa_2022_sig %>% filter(province_en %in% central)\neastern_lisa_2022_sig <- lisa_2022_sig %>% filter(province_en %in% eastern)\nsouthern_lisa_2022_sig <- lisa_2022_sig %>% filter(province_en %in% southern)\n```\n:::\n\n\n### Northeastern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nnortheastern_local <- tm_shape(northeastern_lisa_2022)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nnortheastern_sig <- tm_shape(northeastern_lisa_2022)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(northeastern_local,northeastern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-155-1.png){width=1152}\n:::\n:::\n\n\n### Northern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nnorthern_local <- tm_shape(northern_lisa_2022)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nnorthern_sig <- tm_shape(northern_lisa_2022)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(northern_local,northern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-156-1.png){width=1152}\n:::\n:::\n\n\n### Western Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nwestern_local <- tm_shape(western_lisa_2022)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nwestern_sig <- tm_shape(western_lisa_2022)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(western_local,western_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-157-1.png){width=1152}\n:::\n:::\n\n\n### Central Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ncentral_local <- tm_shape(central_lisa_2022)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ncentral_sig <- tm_shape(central_lisa_2022)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(central_local,central_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-158-1.png){width=1152}\n:::\n:::\n\n\n### Eastern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\neastern_local <- tm_shape(eastern_lisa_2022)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\neastern_sig <- tm_shape(eastern_lisa_2022)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(eastern_local,eastern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-159-1.png){width=1152}\n:::\n:::\n\n\n### Southern Region\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nsouthern_local <- tm_shape(southern_lisa_2022)+\n  tm_fill(\"ii\", \n          palette = c(\"#e1ecbb\",\"#f5f3a6\", \"#ec9a64\",\"#de573e\",\"#d21b1c\"),\n          title = \"Local Moran's I\",\n          midpoint = NA) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Village-Level Spatial Autocorrelation \\nof drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\nsouthern_sig <- tm_shape(southern_lisa_2022)+\n  tm_fill(\"p_ii_sim\", \n          palette = c(\"#d21b1c\",\"#ec9a64\",\"#f5f3a6\",\"#c9e3d2\",\"#b7dce9\"),\n          n =5,\n          title = \"p-value\",\n          midpoint = 0.5) +\n  tm_borders(col = \"black\", alpha = 0.6)+\n  tm_layout(main.title = \"Statistical Significance of Spatial Autocorrelation\\n of drug use Cases in North District\",\n            main.title.position = \"center\",\n            main.title.size = 1.3,\n            main.title.fontface = \"bold\",\n            legend.title.size = 1,\n            legend.text.size = 0.8,\n            frame = TRUE) +\n  tm_borders(alpha = 0.5) +\n  tm_compass(type=\"8star\", text.size = 1, size = 2, position=c(\"RIGHT\", \"TOP\")) +\n  tm_scale_bar(position=c(\"LEFT\", \"BOTTOM\"), text.size=1) +\n  tm_grid(labels.size = 1,alpha =0.2)\n\ntmap_arrange(southern_local,southern_sig, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-160-1.png){width=1152}\n:::\n:::\n\n\n### Analysis & Discussion\n\nThe central district\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ntm_shape(central_lisa_2022)+\n  tm_polygons(id=\"label\") +\n  tm_borders(col = \"black\", alpha = 0.6)+\ntm_shape(central_lisa_2022_sig)+\n  tm_fill(\"ii\", \n          palette = c(\"#b7dce9\",\"#e1ecbb\"),\n          title = \"Local Moran's I (p < 0.05)\",\n          midpoint = NA,\n          id=\"label\")+\n  tm_borders(col = \"black\", alpha = 0.6)\n```\n\n::: {.cell-output-display}\n![](Take-home_ex02_files/figure-html/unnamed-chunk-161-1.png){width=672}\n:::\n:::\n\n:::\n\n\n## 2.7.3 LISA Classification\n",
    "supporting": [
      "Take-home_ex02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}